-- H2 原生 DDL（dev 启动时由 Spring Boot 自动加载 classpath:schema.sql）
CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    real_name VARCHAR(64),
    role VARCHAR(32) NOT NULL DEFAULT 'VIEWER',
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sys_menu (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    parent_id BIGINT DEFAULT 0,
    name VARCHAR(64) NOT NULL,
    code VARCHAR(128),
    path VARCHAR(255),
    icon VARCHAR(64),
    sort_order INT DEFAULT 0,
    status TINYINT DEFAULT 1,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS fac_device (
    device_code CHAR(20) PRIMARY KEY,
    device_name VARCHAR(128) NOT NULL,
    device_type VARCHAR(32),
    zone VARCHAR(64),
    status TINYINT NOT NULL DEFAULT 0,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS fac_alarm (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    alarm_id VARCHAR(32),
    device_code CHAR(20),
    level TINYINT NOT NULL,
    type VARCHAR(32),
    title VARCHAR(255) NOT NULL,
    content TEXT,
    status TINYINT NOT NULL DEFAULT 0,
    occurred_at TIMESTAMP NOT NULL,
    location VARCHAR(128),
    category VARCHAR(32),
    warned BOOLEAN DEFAULT FALSE,
    plan_id VARCHAR(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0
);
