-- V27 应急指挥指令（真实数据源，替代原 EmergencyService 硬编码常量）。
-- 列表来自 fac_emergency_cmd；详情富文本（派发对象/日志/媒体）存于 detail_json。
CREATE TABLE fac_emergency_cmd (
    id VARCHAR(64) NOT NULL,
    grp_id VARCHAR(64) NOT NULL,
    grp_label VARCHAR(128) NOT NULL,
    grp_tab VARCHAR(32) NOT NULL,
    instruction_type VARCHAR(32),
    name VARCHAR(128),
    location VARCHAR(256),
    status VARCHAR(32),
    action_label VARCHAR(64),
    done BOOLEAN,
    detail_json LONGVARCHAR,
    PRIMARY KEY (id)
);

INSERT INTO fac_emergency_cmd (id, grp_id, grp_label, grp_tab, instruction_type, name, location, status, action_label, done, detail_json) VALUES (
    'n1', 'notify', '一键通知', 'fixed', '通知', '通知值班人员', '中海壳牌石油化工有限公司', '待处置', NULL, FALSE,
    '{"notifyChannels": ["app", "sms", "voice"], "dispatchMode": "自动派发", "description": "【2026-04-27 14:55:24】装置区发生疑似火灾事故，请按预案开展通知与前置处置，保持信息同步。", "attachment": "—", "addressBookRecipients": [{"id": "ab1", "role": "公司总值班室", "name": "宋文帅", "phone": "13792536966"}, {"id": "ab2", "role": "消防一队", "name": "王钰", "phone": "18300556145"}, {"id": "ab3", "role": "工艺处置组", "name": "高策", "phone": "18300556146"}], "dutyRecipients": [{"id": "dy1", "role": "值班领导", "name": "杨恒朋", "phone": "13792536966"}, {"id": "dy2", "role": "值班员", "name": "高颖", "phone": "18300556145"}], "dynamics": [{"id": "n1-1", "time": "2026-04-27 14:56:10", "type": "系统", "operator": "应急指挥平台", "result": "已记录", "content": "根据公司级应急预案自动生成“通知值班人员”指令，共匹配 6 名当日值班人员。"}, {"id": "n1-2", "time": "2026-04-27 14:56:24", "type": "派发", "operator": "指挥员 杨恒朋", "result": "成功", "content": "指令已发送至公司总值班室、炼油分部值班组及装置当班人员；APP 6/6 送达，短信 6/6 送达。"}, {"id": "n1-3", "time": "2026-04-27 14:57:03", "type": "签收", "operator": "值班领导 杨恒朋", "result": "成功", "content": "已签收指令，确认进入应急指挥室并组织会商研判。"}, {"id": "n1-4", "time": "2026-04-27 14:58:16", "type": "现场反馈", "operator": "装置值班长 高策", "result": "进行中", "content": "当班 23 人已全部确认收到通知，正按分工进行工艺隔离和无关人员清点。", "attachment": "现场人员清点表.xlsx", "media": [{"id": "n1-image", "type": "image", "name": "装置区警戒隔离现场", "src": ""}, {"id": "n1-audio", "type": "audio", "name": "装置值班长现场语音", "duration": "00:18"}]}]}'
);

INSERT INTO fac_emergency_cmd (id, grp_id, grp_label, grp_tab, instruction_type, name, location, status, action_label, done, detail_json) VALUES (
    'n2', 'notify', '一键通知', 'fixed', '通知', '通知消防队伍', '中海壳牌石油化工有限公司', '已处置', NULL, TRUE,
    '{"notifyChannels": ["app", "sms", "voice"], "dispatchMode": "自动派发", "description": "【2026-04-27 14:55:24】装置区发生疑似火灾事故，请按预案开展通知与前置处置，保持信息同步。", "attachment": "—", "addressBookRecipients": [{"id": "ab1", "role": "公司总值班室", "name": "宋文帅", "phone": "13792536966"}, {"id": "ab2", "role": "消防一队", "name": "王钰", "phone": "18300556145"}, {"id": "ab3", "role": "工艺处置组", "name": "高策", "phone": "18300556146"}], "dutyRecipients": [{"id": "dy1", "role": "值班领导", "name": "杨恒朋", "phone": "13792536966"}, {"id": "dy2", "role": "值班员", "name": "高颖", "phone": "18300556145"}], "dynamics": [{"id": "n2-1", "time": "2026-04-27 14:56:18", "type": "系统", "operator": "应急指挥平台", "result": "已记录", "content": "事件等级达到公司级响应条件，自动生成消防队伍通知指令。"}, {"id": "n2-2", "time": "2026-04-27 14:56:31", "type": "派发", "operator": "指挥员 杨恒朋", "result": "成功", "content": "炼油消防一中队 18 人、重型泡沫车 1 辆已完成通知。"}, {"id": "n2-3", "time": "2026-04-27 14:56:48", "type": "签收", "operator": "消防一中队 王钰", "result": "成功", "content": "队伍已签收，完成个人防护与泡沫液装载检查。"}, {"id": "n2-4", "time": "2026-04-27 14:58:05", "type": "执行", "operator": "消防一中队 王钰", "result": "进行中", "content": "消防车组已出发，由北二门进入，距事故点 0.8km。"}, {"id": "n2-5", "time": "2026-04-27 15:01:18", "type": "完成", "operator": "现场指挥 王钰", "result": "已完成", "content": "消防力量已到达指定集结点，人员、车辆及装备清点完成，通知指令办结。", "media": [{"id": "n2-image", "type": "image", "name": "消防力量到场回传", "src": ""}, {"id": "n2-video", "type": "video", "name": "消防车集结现场视频", "src": "", "duration": "00:26"}]}]}'
);

INSERT INTO fac_emergency_cmd (id, grp_id, grp_label, grp_tab, instruction_type, name, location, status, action_label, done, detail_json) VALUES (
    'n3', 'notify', '一键通知', 'fixed', '通知', '通知工艺处置组', '中海壳牌石油化工有限公司', '待处置', NULL, FALSE,
    '{"notifyChannels": ["app", "sms", "voice"], "dispatchMode": "自动派发", "description": "【2026-04-27 14:55:24】装置区发生疑似火灾事故，请按预案开展通知与前置处置，保持信息同步。", "attachment": "—", "addressBookRecipients": [{"id": "ab1", "role": "公司总值班室", "name": "宋文帅", "phone": "13792536966"}, {"id": "ab2", "role": "消防一队", "name": "王钰", "phone": "18300556145"}, {"id": "ab3", "role": "工艺处置组", "name": "高策", "phone": "18300556146"}], "dutyRecipients": [{"id": "dy1", "role": "值班领导", "name": "杨恒朋", "phone": "13792536966"}, {"id": "dy2", "role": "值班员", "name": "高颖", "phone": "18300556145"}], "dynamics": [{"id": "n3-1", "time": "2026-04-27 14:56:22", "type": "系统", "operator": "应急指挥平台", "result": "已记录", "content": "已生成工艺处置组通知，关联装置紧急停车与物料隔离卡。"}, {"id": "n3-2", "time": "2026-04-27 14:56:45", "type": "派发", "operator": "指挥员 杨恒朋", "result": "成功", "content": "指令已发送给工艺处置组 8 人，要求确认泄漏介质、切断上游物料并建立盲板隔离清单。"}, {"id": "n3-3", "time": "2026-04-27 14:58:34", "type": "现场反馈", "operator": "工艺处置组 高策", "result": "进行中", "content": "已关闭上游紧急切断阀 XV-1203，现场可燃气体检测值正在下降；东侧阀组渗漏点仍需进一步确认。", "attachment": "现场气体检测记录.pdf", "media": [{"id": "n3-image", "type": "image", "name": "东侧阀组泄漏点", "src": ""}, {"id": "n3-audio", "type": "audio", "name": "工艺组现场反馈", "duration": "00:32"}]}, {"id": "n3-4", "time": "2026-04-27 14:59:12", "type": "异常", "operator": "工艺处置组 高策", "result": "异常", "content": "东侧手动阀周边温度偏高，现场人员无法近距离操作，申请消防水幕掩护后再实施关阀。", "media": [{"id": "n3-video", "type": "video", "name": "东侧阀组热辐射现场", "src": "", "duration": "00:41"}]}]}'
);

INSERT INTO fac_emergency_cmd (id, grp_id, grp_label, grp_tab, instruction_type, name, location, status, action_label, done, detail_json) VALUES (
    'd1', 'dispatch', '一键调度', 'fixed', '任务', '调度消防一队', '中海壳牌石油化工有限公司', '待派发', '一键派发', NULL,
    '{"notifyChannels": ["app", "sms", "voice"], "dispatchMode": "自动派发", "description": "【2026-04-27 14:55:24】装置区发生疑似火灾事故，请按预案开展通知与前置处置，保持信息同步。", "attachment": "—", "addressBookRecipients": [{"id": "ab1", "role": "公司总值班室", "name": "宋文帅", "phone": "13792536966"}, {"id": "ab2", "role": "消防一队", "name": "王钰", "phone": "18300556145"}, {"id": "ab3", "role": "工艺处置组", "name": "高策", "phone": "18300556146"}], "dutyRecipients": [{"id": "dy1", "role": "值班领导", "name": "杨恒朋", "phone": "13792536966"}, {"id": "dy2", "role": "值班员", "name": "高颖", "phone": "18300556145"}], "dynamics": [{"id": "d1-1", "time": "2026-04-27 14:57:05", "type": "系统", "operator": "应急指挥平台", "result": "已记录", "content": "已根据事故位置、队伍状态和专业能力匹配炼油消防一中队。"}, {"id": "d1-2", "time": "2026-04-27 14:57:18", "type": "派发", "operator": "指挥员 杨恒朋", "result": "进行中", "content": "调度单已生成，待指挥员确认派发；任务包含冷却抑爆、泡沫覆盖和现场侦检。"}]}'
);

INSERT INTO fac_emergency_cmd (id, grp_id, grp_label, grp_tab, instruction_type, name, location, status, action_label, done, detail_json) VALUES (
    'd2', 'dispatch', '一键调度', 'fixed', '任务', '调度泡沫车', '中海壳牌石油化工有限公司', '已处置', NULL, TRUE,
    '{"notifyChannels": ["app", "sms", "voice"], "dispatchMode": "自动派发", "description": "【2026-04-27 14:55:24】装置区发生疑似火灾事故，请按预案开展通知与前置处置，保持信息同步。", "attachment": "—", "addressBookRecipients": [{"id": "ab1", "role": "公司总值班室", "name": "宋文帅", "phone": "13792536966"}, {"id": "ab2", "role": "消防一队", "name": "王钰", "phone": "18300556145"}, {"id": "ab3", "role": "工艺处置组", "name": "高策", "phone": "18300556146"}], "dutyRecipients": [{"id": "dy1", "role": "值班领导", "name": "杨恒朋", "phone": "13792536966"}, {"id": "dy2", "role": "值班员", "name": "高颖", "phone": "18300556145"}], "dynamics": [{"id": "d2-1", "time": "2026-04-27 14:57:12", "type": "派发", "operator": "指挥员 杨恒朋", "result": "成功", "content": "重型泡沫车及 3 名车组人员已接收调度任务。"}, {"id": "d2-2", "time": "2026-04-27 14:58:20", "type": "执行", "operator": "车组长 陈伟", "result": "进行中", "content": "车辆已出库，泡沫液 6t、水 12t，装备状态正常。"}, {"id": "d2-3", "time": "2026-04-27 15:00:42", "type": "现场反馈", "operator": "车组长 陈伟", "result": "进行中", "content": "车辆已在事故点东北侧停靠，正连接 8 号消防栓和泡沫比例混合器。", "media": [{"id": "d2-image", "type": "image", "name": "泡沫车供液干线现场", "src": ""}, {"id": "d2-audio", "type": "audio", "name": "车组长到场报告", "duration": "00:14"}]}, {"id": "d2-4", "time": "2026-04-27 15:02:06", "type": "完成", "operator": "现场指挥 王钰", "result": "已完成", "content": "泡沫车已建立供液干线并开始持续供泡沫，调度任务完成。"}]}'
);

INSERT INTO fac_emergency_cmd (id, grp_id, grp_label, grp_tab, instruction_type, name, location, status, action_label, done, detail_json) VALUES (
    'd3', 'dispatch', '一键调度', 'fixed', '任务', '调度医疗救护', '中海壳牌石油化工有限公司', '待派发', '一键派发', NULL,
    '{"notifyChannels": ["app", "sms", "voice"], "dispatchMode": "自动派发", "description": "【2026-04-27 14:55:24】装置区发生疑似火灾事故，请按预案开展通知与前置处置，保持信息同步。", "attachment": "—", "addressBookRecipients": [{"id": "ab1", "role": "公司总值班室", "name": "宋文帅", "phone": "13792536966"}, {"id": "ab2", "role": "消防一队", "name": "王钰", "phone": "18300556145"}, {"id": "ab3", "role": "工艺处置组", "name": "高策", "phone": "18300556146"}], "dutyRecipients": [{"id": "dy1", "role": "值班领导", "name": "杨恒朋", "phone": "13792536966"}, {"id": "dy2", "role": "值班员", "name": "高颖", "phone": "18300556145"}], "dynamics": [{"id": "d3-1", "time": "2026-04-27 14:57:24", "type": "系统", "operator": "应急指挥平台", "result": "已记录", "content": "已生成医疗救护待命任务，关联厂区医务室和 120 联动联系人。"}, {"id": "d3-2", "time": "2026-04-27 14:57:36", "type": "派发", "operator": "指挥员 杨恒朋", "result": "进行中", "content": "调度任务待确认派发，要求配备吸氧、烧伤急救和化学品暴露处置物资。"}]}'
);

INSERT INTO fac_emergency_cmd (id, grp_id, grp_label, grp_tab, instruction_type, name, location, status, action_label, done, detail_json) VALUES (
    't1', 'temp-notify', '临时通知', 'temp', '通知', '通知周边企业', '大亚湾石化区', '待处置', NULL, FALSE,
    '{"notifyChannels": ["app", "sms", "voice"], "dispatchMode": "自动派发", "description": "【2026-04-27 14:55:24】装置区发生疑似火灾事故，请按预案开展通知与前置处置，保持信息同步。", "attachment": "—", "addressBookRecipients": [{"id": "ab1", "role": "公司总值班室", "name": "宋文帅", "phone": "13792536966"}, {"id": "ab2", "role": "消防一队", "name": "王钰", "phone": "18300556145"}, {"id": "ab3", "role": "工艺处置组", "name": "高策", "phone": "18300556146"}], "dutyRecipients": [{"id": "dy1", "role": "值班领导", "name": "杨恒朋", "phone": "13792536966"}, {"id": "dy2", "role": "值班员", "name": "高颖", "phone": "18300556145"}], "dynamics": [{"id": "t1-1", "time": "2026-04-27 14:59:08", "type": "系统", "operator": "应急指挥平台", "result": "已记录", "content": "根据气象风向和扩散模型，生成下风向周边单位风险提醒通知。"}, {"id": "t1-2", "time": "2026-04-27 14:59:30", "type": "派发", "operator": "指挥员 杨恒朋", "result": "进行中", "content": "通知草稿已完成，待复核扩散影响范围后正式发送。"}]}'
);

INSERT INTO fac_emergency_cmd (id, grp_id, grp_label, grp_tab, instruction_type, name, location, status, action_label, done, detail_json) VALUES (
    't2', 'temp-dispatch', '临时调度', 'temp', '任务', '增派泡沫灭火剂', '应急物资库', '待派发', '一键派发', NULL,
    '{"notifyChannels": ["app", "sms", "voice"], "dispatchMode": "自动派发", "description": "【2026-04-27 14:55:24】装置区发生疑似火灾事故，请按预案开展通知与前置处置，保持信息同步。", "attachment": "—", "addressBookRecipients": [{"id": "ab1", "role": "公司总值班室", "name": "宋文帅", "phone": "13792536966"}, {"id": "ab2", "role": "消防一队", "name": "王钰", "phone": "18300556145"}, {"id": "ab3", "role": "工艺处置组", "name": "高策", "phone": "18300556146"}], "dutyRecipients": [{"id": "dy1", "role": "值班领导", "name": "杨恒朋", "phone": "13792536966"}, {"id": "dy2", "role": "值班员", "name": "高颖", "phone": "18300556145"}], "dynamics": [{"id": "t2-1", "time": "2026-04-27 15:00:05", "type": "系统", "operator": "应急指挥平台", "result": "已记录", "content": "根据泡沫液消耗速率生成增援建议：增派抗溶性水成膜泡沫液 4t。"}, {"id": "t2-2", "time": "2026-04-27 15:00:22", "type": "派发", "operator": "物资保障组 赵敏", "result": "进行中", "content": "已预占库存 4t，待调度指令确认后出库。"}]}'
);
