-- V31 应急流程全景真实数据源（fm-accident-rescue 应急指挥 · 流程节点全景 / 节点处置指引）。
-- 数据来源：src/screen/lib/data/emergencyProcessData.ts（5 阶段 / 4 响应模式 / 15 流程节点）与
-- nodeGuidanceData.ts（9 条节点处置指引 + 实时值班表）；由脚本从上述 TS 常量直出，数值与文案逐一对齐。
-- 嵌套结构（动作清单 / 判据清单 / 升级规则 / 上报链路 / 岗位任务）序列化为 detail_json LONGVARCHAR，
-- 与 V27 fac_emergency_cmd.detail_json 同范式；阶段与响应模式为扁平结构，用显式列存储。
-- 列名回避保留字（start/end/status）：start_stage / end_stage / mode_code / mode_label。

CREATE TABLE fac_emergency_phase (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    phase_code VARCHAR(32) NOT NULL,
    phase_name VARCHAR(64) NOT NULL,
    start_stage INT NOT NULL,
    end_stage INT NOT NULL,
    tone VARCHAR(16) NOT NULL,
    sort_no INT NOT NULL DEFAULT 0
);

CREATE TABLE fac_emergency_response_mode (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    mode_code VARCHAR(32) NOT NULL,
    mode_label VARCHAR(64) NOT NULL,
    stage_id INT NOT NULL,
    sort_no INT NOT NULL DEFAULT 0
);

CREATE TABLE fac_emergency_process_stage (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    stage_id INT NOT NULL,
    phase_code VARCHAR(32) NOT NULL,
    detail_json LONGVARCHAR NOT NULL,
    sort_no INT NOT NULL DEFAULT 0
);

CREATE TABLE fac_emergency_node_guidance (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    node_id VARCHAR(16) NOT NULL,
    detail_json LONGVARCHAR NOT NULL,
    sort_no INT NOT NULL DEFAULT 0
);

CREATE TABLE fac_emergency_guidance_roster (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    shift_group VARCHAR(64) NOT NULL,
    supervisor VARCHAR(128) NOT NULL,
    supervisor_phone VARCHAR(32) NOT NULL,
    board_operator VARCHAR(128) NOT NULL,
    board_operator_phone VARCHAR(32) NOT NULL,
    field_operator VARCHAR(128) NOT NULL,
    field_operator_phone VARCHAR(32) NOT NULL,
    sort_no INT NOT NULL DEFAULT 0
);

-- 5 个应急阶段
INSERT INTO fac_emergency_phase (phase_code, phase_name, start_stage, end_stage, tone, sort_no) VALUES ('phase-team', '班组处置', 1, 4, 'blue', 1);
INSERT INTO fac_emergency_phase (phase_code, phase_name, start_stage, end_stage, tone, sort_no) VALUES ('phase-plant', '运行部级应急', 5, 7, 'cyan', 2);
INSERT INTO fac_emergency_phase (phase_code, phase_name, start_stage, end_stage, tone, sort_no) VALUES ('phase-company', '公司级应急', 8, 10, 'amber', 3);
INSERT INTO fac_emergency_phase (phase_code, phase_name, start_stage, end_stage, tone, sort_no) VALUES ('phase-gov', '政府级应急', 11, 13, 'red', 4);
INSERT INTO fac_emergency_phase (phase_code, phase_name, start_stage, end_stage, tone, sort_no) VALUES ('phase-close', '收尾阶段', 14, 15, 'green', 5);

-- 4 个响应模式（登台/升级下拉选项）
INSERT INTO fac_emergency_response_mode (mode_code, mode_label, stage_id, sort_no) VALUES ('team', '一、班组处置', 1, 1);
INSERT INTO fac_emergency_response_mode (mode_code, mode_label, stage_id, sort_no) VALUES ('plant', '二、运行部级应急', 5, 2);
INSERT INTO fac_emergency_response_mode (mode_code, mode_label, stage_id, sort_no) VALUES ('company', '三、公司级应急', 8, 3);
INSERT INTO fac_emergency_response_mode (mode_code, mode_label, stage_id, sort_no) VALUES ('government', '四、政府级应急', 11, 4);

-- 15 个流程节点（previousContext/currentActions/criteriaChecklist/escalationRule 存 detail_json）
INSERT INTO fac_emergency_process_stage (stage_id, phase_code, detail_json, sort_no) VALUES (1, 'phase-team', '{"id":1,"name":"接警研判","shortName":"1. 接警研判","leadRole":"🧑 现场第一发现人 / 岗位带班","leadTitle":"巡检员 / 内操员","commandLevel":"班组处置","description":"通过巡检、仪器报警第一时间捕捉险情，按三要素（地点、介质、伤员）上报。","previousContext":["10:00:00 - 厂区 GDS 检测到气体异常","10:00:15 - 发现 T103 塔底法兰渗漏"],"currentActions":[{"id":"act-1-1","label":"按三要素向运行部调度核实报告","done":true,"type":"primary"},{"id":"act-1-2","label":"佩戴防护对现场建立初始警戒","done":true}],"criteriaChecklist":[{"id":"cri-1-1","label":"确定事故点位与介质","checked":true},{"id":"cri-1-2","label":"完成初步信息上报","checked":true}],"escalationRule":{"triggerCondition":"确认工况异常或发生真实泄漏，启动班组初始应急","fromRole":"现场第一发现人","toRole":"现场班组长","details":{"location":"加氢制氢部 T103 塔底泵 P101B 处","substance":"加氢裂化重油 / 硫化氢（H2S）","casualty":"无人员受伤","currentStatus":"现场有轻度泄漏，报警系统正常响应"}}}', 1);
INSERT INTO fac_emergency_process_stage (stage_id, phase_code, detail_json, sort_no) VALUES (2, 'phase-team', '{"id":2,"name":"一分钟应急响应与能量隔离","shortName":"2. 一分钟应急响应","leadRole":"🧑‍💼 现场班组长（岗位带班）","leadTitle":"加氢班组长","commandLevel":"班组处置","description":"一分钟内落实“该停的停、该关的关、该放的放”，执行能量隔离与物料切断。","previousContext":["10:00:30 - 已完成接警研判"],"currentActions":[{"id":"act-2-1","label":"DCS 一键急停与切断联锁","done":true,"type":"danger"},{"id":"act-2-2","label":"停运 P101B，关闭进料阀","done":true},{"id":"act-2-3","label":"开启紧急泄压阀门降压","done":true}],"criteriaChecklist":[{"id":"cri-2-1","label":"能量隔离阀关毕率 100%","checked":true},{"id":"cri-2-2","label":"无关人员撤至上风向","checked":true}],"escalationRule":{"triggerCondition":"一分钟能量隔离完成，申请运行部级预案评定","fromRole":"现场班组长","toRole":"运行部区域主管","details":{"location":"T103 塔及泵房区域","substance":"加氢裂化重油","casualty":"0人受伤","currentStatus":"进料切断完成，塔压下降中"}}}', 2);
INSERT INTO fac_emergency_process_stage (stage_id, phase_code, detail_json, sort_no) VALUES (3, 'phase-team', '{"id":3,"name":"三分钟退守稳态","shortName":"3. 三分钟退守稳态","leadRole":"🧑‍💻 运行部区域主管","leadTitle":"加氢运行部主管","commandLevel":"班组处置","description":"三分钟内完成工艺退守稳态：降温降压、物料导空、系统隔离。","previousContext":["10:01:00 - 能量隔离完成"],"currentActions":[{"id":"act-3-1","label":"降温降压退守稳态","done":true},{"id":"act-3-2","label":"物料导空并完成系统隔离","done":false,"type":"warning"},{"id":"act-3-3","label":"评估是否达到升级条件","done":false,"type":"primary"}],"criteriaChecklist":[{"id":"cri-3-1","label":"塔体压力降至安全阈值","checked":true},{"id":"cri-3-2","label":"泄漏点气体浓度受控","checked":false}],"escalationRule":{"triggerCondition":"退守稳态期间泄漏扩大或浓度超限，升级至运行部级预案","fromRole":"运行部区域主管","toRole":"运行部级应急指挥部","details":{"location":"加氢裂化装置区","substance":"加氢裂化重油 / 硫化氢","casualty":"0人受伤","currentStatus":"塔压下降中，仍有少量介质渗出"}}}', 3);
INSERT INTO fac_emergency_process_stage (stage_id, phase_code, detail_json, sort_no) VALUES (4, 'phase-team', '{"id":4,"name":"五分钟消气防联动","shortName":"4. 五分钟消气防联动","leadRole":"🚒 消气防救援力量","leadTitle":"消气防指挥","commandLevel":"班组处置","description":"五分钟内消气防联动：水幕隔离、泄漏稀释、人员清点，防止气体扩散形成闪爆。","previousContext":["10:02:00 - 申请消气防联动"],"currentActions":[{"id":"act-4-1","label":"启动水幕隔离与泄漏稀释","done":false,"type":"danger"},{"id":"act-4-2","label":"气体浓度连续监测与警戒","done":false},{"id":"act-4-3","label":"全装置人员清点确认","done":false}],"criteriaChecklist":[{"id":"cri-4-1","label":"下风向 100m 内无人员","checked":false},{"id":"cri-4-2","label":"气体浓度不再上升","checked":false}],"escalationRule":{"triggerCondition":"班组处置无法控制，需升级至运行部级应急","fromRole":"消气防指挥","toRole":"运行部级应急指挥部","details":{"location":"加氢裂化装置区及周边","substance":"加氢裂化重油 / 硫化氢","casualty":"0人受伤","currentStatus":"水幕已启动，浓度持续监测中"}}}', 4);
INSERT INTO fac_emergency_process_stage (stage_id, phase_code, detail_json, sort_no) VALUES (5, 'phase-plant', '{"id":5,"name":"运行部级应急·节点1","shortName":"节点1","leadRole":"🧑‍💼 运行部级应急现场指挥","leadTitle":"运行部级应急指挥长","commandLevel":"运行部级应急","description":"按运行部级应急专项预案执行第 1 项处置任务，落实力量部署、工艺控制与态势上报。","previousContext":["上一节点已完成，进入运行部级应急节点1"],"currentActions":[{"id":"act-5-1","label":"落实运行部级应急节点1处置指令","done":false,"type":"primary"},{"id":"act-5-2","label":"同步上报现场态势与处置进展","done":false}],"criteriaChecklist":[{"id":"cri-5-1","label":"运行部级应急节点1关键动作完成","checked":false},{"id":"cri-5-2","label":"现场态势受控或具备升级条件","checked":false}],"escalationRule":{"triggerCondition":"当前级别处置无法控制险情，需升级到上一级应急响应","fromRole":"当前级别现场指挥","toRole":"上一级应急指挥部","details":{"location":"加氢裂化装置区","substance":"加氢裂化重油 / 硫化氢","casualty":"0人受伤","currentStatus":"现场处置推进中"}}}', 5);
INSERT INTO fac_emergency_process_stage (stage_id, phase_code, detail_json, sort_no) VALUES (6, 'phase-plant', '{"id":6,"name":"运行部级应急·节点2","shortName":"节点2","leadRole":"🧑‍💼 运行部级应急现场指挥","leadTitle":"运行部级应急指挥长","commandLevel":"运行部级应急","description":"按运行部级应急专项预案执行第 2 项处置任务，落实力量部署、工艺控制与态势上报。","previousContext":["上一节点已完成，进入运行部级应急节点2"],"currentActions":[{"id":"act-6-1","label":"落实运行部级应急节点2处置指令","done":false,"type":"primary"},{"id":"act-6-2","label":"同步上报现场态势与处置进展","done":false}],"criteriaChecklist":[{"id":"cri-6-1","label":"运行部级应急节点2关键动作完成","checked":false},{"id":"cri-6-2","label":"现场态势受控或具备升级条件","checked":false}],"escalationRule":{"triggerCondition":"当前级别处置无法控制险情，需升级到上一级应急响应","fromRole":"当前级别现场指挥","toRole":"上一级应急指挥部","details":{"location":"加氢裂化装置区","substance":"加氢裂化重油 / 硫化氢","casualty":"0人受伤","currentStatus":"现场处置推进中"}}}', 6);
INSERT INTO fac_emergency_process_stage (stage_id, phase_code, detail_json, sort_no) VALUES (7, 'phase-plant', '{"id":7,"name":"运行部级应急·节点3","shortName":"节点3","leadRole":"🧑‍💼 运行部级应急现场指挥","leadTitle":"运行部级应急指挥长","commandLevel":"运行部级应急","description":"按运行部级应急专项预案执行第 3 项处置任务，落实力量部署、工艺控制与态势上报。","previousContext":["上一节点已完成，进入运行部级应急节点3"],"currentActions":[{"id":"act-7-1","label":"落实运行部级应急节点3处置指令","done":false,"type":"primary"},{"id":"act-7-2","label":"同步上报现场态势与处置进展","done":false}],"criteriaChecklist":[{"id":"cri-7-1","label":"运行部级应急节点3关键动作完成","checked":false},{"id":"cri-7-2","label":"现场态势受控或具备升级条件","checked":false}],"escalationRule":{"triggerCondition":"当前级别处置无法控制险情，需升级到上一级应急响应","fromRole":"当前级别现场指挥","toRole":"上一级应急指挥部","details":{"location":"加氢裂化装置区","substance":"加氢裂化重油 / 硫化氢","casualty":"0人受伤","currentStatus":"现场处置推进中"}}}', 7);
INSERT INTO fac_emergency_process_stage (stage_id, phase_code, detail_json, sort_no) VALUES (8, 'phase-company', '{"id":8,"name":"公司级应急·节点1","shortName":"节点1","leadRole":"🧑‍💼 公司级应急现场指挥","leadTitle":"公司级应急指挥长","commandLevel":"公司级应急","description":"按公司级应急专项预案执行第 1 项处置任务，落实力量部署、工艺控制与态势上报。","previousContext":["上一节点已完成，进入公司级应急节点1"],"currentActions":[{"id":"act-8-1","label":"落实公司级应急节点1处置指令","done":false,"type":"primary"},{"id":"act-8-2","label":"同步上报现场态势与处置进展","done":false}],"criteriaChecklist":[{"id":"cri-8-1","label":"公司级应急节点1关键动作完成","checked":false},{"id":"cri-8-2","label":"现场态势受控或具备升级条件","checked":false}],"escalationRule":{"triggerCondition":"当前级别处置无法控制险情，需升级到上一级应急响应","fromRole":"当前级别现场指挥","toRole":"上一级应急指挥部","details":{"location":"加氢裂化装置区","substance":"加氢裂化重油 / 硫化氢","casualty":"0人受伤","currentStatus":"现场处置推进中"}}}', 8);
INSERT INTO fac_emergency_process_stage (stage_id, phase_code, detail_json, sort_no) VALUES (9, 'phase-company', '{"id":9,"name":"公司级应急·节点2","shortName":"节点2","leadRole":"🧑‍💼 公司级应急现场指挥","leadTitle":"公司级应急指挥长","commandLevel":"公司级应急","description":"按公司级应急专项预案执行第 2 项处置任务，落实力量部署、工艺控制与态势上报。","previousContext":["上一节点已完成，进入公司级应急节点2"],"currentActions":[{"id":"act-9-1","label":"落实公司级应急节点2处置指令","done":false,"type":"primary"},{"id":"act-9-2","label":"同步上报现场态势与处置进展","done":false}],"criteriaChecklist":[{"id":"cri-9-1","label":"公司级应急节点2关键动作完成","checked":false},{"id":"cri-9-2","label":"现场态势受控或具备升级条件","checked":false}],"escalationRule":{"triggerCondition":"当前级别处置无法控制险情，需升级到上一级应急响应","fromRole":"当前级别现场指挥","toRole":"上一级应急指挥部","details":{"location":"加氢裂化装置区","substance":"加氢裂化重油 / 硫化氢","casualty":"0人受伤","currentStatus":"现场处置推进中"}}}', 9);
INSERT INTO fac_emergency_process_stage (stage_id, phase_code, detail_json, sort_no) VALUES (10, 'phase-company', '{"id":10,"name":"公司级应急·节点3","shortName":"节点3","leadRole":"🧑‍💼 公司级应急现场指挥","leadTitle":"公司级应急指挥长","commandLevel":"公司级应急","description":"按公司级应急专项预案执行第 3 项处置任务，落实力量部署、工艺控制与态势上报。","previousContext":["上一节点已完成，进入公司级应急节点3"],"currentActions":[{"id":"act-10-1","label":"落实公司级应急节点3处置指令","done":false,"type":"primary"},{"id":"act-10-2","label":"同步上报现场态势与处置进展","done":false}],"criteriaChecklist":[{"id":"cri-10-1","label":"公司级应急节点3关键动作完成","checked":false},{"id":"cri-10-2","label":"现场态势受控或具备升级条件","checked":false}],"escalationRule":{"triggerCondition":"当前级别处置无法控制险情，需升级到上一级应急响应","fromRole":"当前级别现场指挥","toRole":"上一级应急指挥部","details":{"location":"加氢裂化装置区","substance":"加氢裂化重油 / 硫化氢","casualty":"0人受伤","currentStatus":"现场处置推进中"}}}', 10);
INSERT INTO fac_emergency_process_stage (stage_id, phase_code, detail_json, sort_no) VALUES (11, 'phase-gov', '{"id":11,"name":"政府级应急·节点1","shortName":"节点1","leadRole":"🧑‍💼 政府级应急现场指挥","leadTitle":"政府级应急指挥长","commandLevel":"政府级应急","description":"按政府级应急专项预案执行第 1 项处置任务，落实力量部署、工艺控制与态势上报。","previousContext":["上一节点已完成，进入政府级应急节点1"],"currentActions":[{"id":"act-11-1","label":"落实政府级应急节点1处置指令","done":false,"type":"primary"},{"id":"act-11-2","label":"同步上报现场态势与处置进展","done":false}],"criteriaChecklist":[{"id":"cri-11-1","label":"政府级应急节点1关键动作完成","checked":false},{"id":"cri-11-2","label":"现场态势受控或具备升级条件","checked":false}],"escalationRule":{"triggerCondition":"当前级别处置无法控制险情，需升级到上一级应急响应","fromRole":"当前级别现场指挥","toRole":"上一级应急指挥部","details":{"location":"加氢裂化装置区","substance":"加氢裂化重油 / 硫化氢","casualty":"0人受伤","currentStatus":"现场处置推进中"}}}', 11);
INSERT INTO fac_emergency_process_stage (stage_id, phase_code, detail_json, sort_no) VALUES (12, 'phase-gov', '{"id":12,"name":"政府级应急·节点2","shortName":"节点2","leadRole":"🧑‍💼 政府级应急现场指挥","leadTitle":"政府级应急指挥长","commandLevel":"政府级应急","description":"按政府级应急专项预案执行第 2 项处置任务，落实力量部署、工艺控制与态势上报。","previousContext":["上一节点已完成，进入政府级应急节点2"],"currentActions":[{"id":"act-12-1","label":"落实政府级应急节点2处置指令","done":false,"type":"primary"},{"id":"act-12-2","label":"同步上报现场态势与处置进展","done":false}],"criteriaChecklist":[{"id":"cri-12-1","label":"政府级应急节点2关键动作完成","checked":false},{"id":"cri-12-2","label":"现场态势受控或具备升级条件","checked":false}],"escalationRule":{"triggerCondition":"当前级别处置无法控制险情，需升级到上一级应急响应","fromRole":"当前级别现场指挥","toRole":"上一级应急指挥部","details":{"location":"加氢裂化装置区","substance":"加氢裂化重油 / 硫化氢","casualty":"0人受伤","currentStatus":"现场处置推进中"}}}', 12);
INSERT INTO fac_emergency_process_stage (stage_id, phase_code, detail_json, sort_no) VALUES (13, 'phase-gov', '{"id":13,"name":"政府级应急·节点3","shortName":"节点3","leadRole":"🧑‍💼 政府级应急现场指挥","leadTitle":"政府级应急指挥长","commandLevel":"政府级应急","description":"按政府级应急专项预案执行第 3 项处置任务，落实力量部署、工艺控制与态势上报。","previousContext":["上一节点已完成，进入政府级应急节点3"],"currentActions":[{"id":"act-13-1","label":"落实政府级应急节点3处置指令","done":false,"type":"primary"},{"id":"act-13-2","label":"同步上报现场态势与处置进展","done":false}],"criteriaChecklist":[{"id":"cri-13-1","label":"政府级应急节点3关键动作完成","checked":false},{"id":"cri-13-2","label":"现场态势受控或具备升级条件","checked":false}],"escalationRule":{"triggerCondition":"当前级别处置无法控制险情，需升级到上一级应急响应","fromRole":"当前级别现场指挥","toRole":"上一级应急指挥部","details":{"location":"加氢裂化装置区","substance":"加氢裂化重油 / 硫化氢","casualty":"0人受伤","currentStatus":"现场处置推进中"}}}', 13);
INSERT INTO fac_emergency_process_stage (stage_id, phase_code, detail_json, sort_no) VALUES (14, 'phase-close', '{"id":14,"name":"应急终止","shortName":"14. 应急终止","leadRole":"✅ 现场处置组","leadTitle":"现场指挥","commandLevel":"收尾阶段","description":"确认泄漏点封堵、气体浓度达标、污染水全部回收，解除现场警戒。","previousContext":["当前级别处置完成，进入收尾"],"currentActions":[{"id":"act-14-1","label":"泄漏点封堵确认","done":false},{"id":"act-14-2","label":"现场气体浓度复测达标","done":false},{"id":"act-14-3","label":"解除警戒与恢复通行","done":false}],"criteriaChecklist":[{"id":"cri-14-1","label":"泄漏源彻底消除","checked":false},{"id":"cri-14-2","label":"无二次衍生隐患","checked":false}],"escalationRule":{"triggerCondition":"处置完成确认后转入总结评估","fromRole":"现场指挥","toRole":"总结评估组","details":{"location":"T103 塔区域","substance":"-","casualty":"0人受伤","currentStatus":"现场处置完成"}}}', 14);
INSERT INTO fac_emergency_process_stage (stage_id, phase_code, detail_json, sort_no) VALUES (15, 'phase-close', '{"id":15,"name":"总结评估与恢复","shortName":"15. 总结评估与恢复","leadRole":"📋 总结评估组","leadTitle":"应急办主任","commandLevel":"收尾阶段","description":"事故原因调查、损害评估、环境跟踪，确认恢复生产条件并归档复盘。","previousContext":["10:40:00 - 应急终止完成"],"currentActions":[{"id":"act-15-1","label":"事故原因调查组成立","done":false},{"id":"act-15-2","label":"设备损害评估与修复计划","done":false},{"id":"act-15-3","label":"恢复生产条件确认","done":false}],"criteriaChecklist":[{"id":"cri-15-1","label":"调查报告完成","checked":false},{"id":"cri-15-2","label":"生产恢复条件具备","checked":false}],"escalationRule":{"triggerCondition":"总结归档完成，应急流程关闭","fromRole":"总结评估组","toRole":"公司应急指挥中心","details":{"location":"茂名石化厂区","substance":"-","casualty":"0人受伤","currentStatus":"总结与恢复进行中"}}}', 15);

-- 实时值班表（指引弹窗与全景页眉共用）
INSERT INTO fac_emergency_guidance_roster (shift_group, supervisor, supervisor_phone, board_operator, board_operator_phone, field_operator, field_operator_phone, sort_no) VALUES ('乙班（白班）', '李明辉（加氢制氢部值班长）', '138-0288-3456', '张建国（DCS 内操人员）', '139-0668-2233', '王安全（现场外操巡检员）', '137-0668-8378', 1);

-- 9 条节点处置指引（reportingChain / roleTasks 存 detail_json）
INSERT INTO fac_emergency_node_guidance (node_id, detail_json, sort_no) VALUES ('1', '{"nodeId":"1","nodeName":"节点 1：接警研判","reportingChain":[{"step":1,"fromRole":"外操 (巡检员·王安全)","toRole":"内操 (控制室·张建国)","method":"防爆对讲机 1 号频道","notice":"立即汇报现场泄漏/火灾具体位号及肉眼观察规模"},{"step":2,"fromRole":"内操 (控制室·张建国)","toRole":"班组长 (现场指挥·李明辉)","method":"中控室直连电话","notice":"通报 DCS 压力温度突变及 ESD 联锁触发情况"},{"step":3,"fromRole":"班组长 (现场指挥·李明辉)","toRole":"公司应急指挥中心 (2233119)","method":"2233119 应急热线","notice":"1分钟内报告事发装置、介质、伤员及初步评估等级"}],"roleTasks":[{"roleName":"内操","roleTitle":"DCS 中控室内操控制员","personName":"张建国","avatarIcon":"🧑‍💻","phone":"139-0668-2233","tasks":["密切监视 DCS 趋势图，核对 T103 塔底泵 P101B 压力、温度、液位突变曲线","核实 ESD 紧急切断阀是否已自动触发，未触发立即手动执行 ESD-101 一键关断","远程关断 P101B 进出口电动阀门，开启 N2 吹扫管路实施惰性化置换","调取防爆摄像头视口并关注 GDS 气体报警探测器实时浓度，持续向班长通报"]},{"roleName":"外操","roleTitle":"现场外操巡检与早期处置员","personName":"王安全","avatarIcon":"🧑‍🔧","phone":"137-0668-8378","tasks":["佩戴 SCBA 正压式空气呼吸器与防静电服，在上风向 100m 建立警戒红线","检查现场消气防水炮及防火堤，开启固定遥控水炮对 T103 塔壁实施降温对冷","核清现场作业人员数量，确认全部安全撤离并阻断无关人员/车辆进入","到达现场入口迎接并引导消气防大队救援车辆快速抵近点位"]},{"roleName":"班长","roleTitle":"现场处置第一责任人（值班长）","personName":"李明辉","avatarIcon":"🧑‍💼","phone":"138-0288-3456","tasks":["全面接管现场早期指挥，核对外操与内操汇报信息，判定事故等级（二级响应）","1分钟内拨打 2233119 向公司应急指挥中心口头报告，请求消气防大队支援","统辖内操能量隔离与外操水炮降温，指令全装置暂停动火与高危作业","保持现场应急通信频道畅通，准备向到场指挥官移交现场控制权"]}],"generalNotice":"⚠ 接警研判阶段切记「安全第一、快速切断」，禁止无防护人员贸然进入泄漏/流洒火核心区。"}', 1);
INSERT INTO fac_emergency_node_guidance (node_id, detail_json, sort_no) VALUES ('2', '{"nodeId":"2","nodeName":"节点 2：一分钟能量隔离","reportingChain":[{"step":1,"fromRole":"班组长 (李明辉)","toRole":"应急指挥部 (总指挥)","method":"应急专网广播","notice":"报告现场一分钟能量切断完成，申请启动公司级二级应急响应"},{"step":2,"fromRole":"应急指挥部 (总指挥)","toRole":"各应急行动组 (消防/医疗/环保)","method":"声光报警器 + 警报系统","notice":"下达集结指令，救援力量 5 分钟内抵近现场"}],"roleTasks":[{"roleName":"内操","roleTitle":"DCS 中控室内操控制员","personName":"张建国","avatarIcon":"🧑‍💻","phone":"139-0668-2233","tasks":["执行上下游系统平稳减量降压，防止超压二次事故","配合指挥部调取实时工艺历史曲线与气象风向数据"]},{"roleName":"外操","roleTitle":"现场外操巡检员","personName":"王安全","avatarIcon":"🧑‍🔧","phone":"137-0668-8378","tasks":["拉设警戒带，配合专业救援队交接现场水炮控制权","确认清净下水切断阀安全关闭，防止污染水体外溢"]},{"roleName":"班长","roleTitle":"现场处置第一责任人","personName":"李明辉","avatarIcon":"🧑‍💼","phone":"138-0288-3456","tasks":["确认一分钟内完成急停、关阀、泄压三件事","向指挥部汇报隔离完成并请求下一步指令"]}],"generalNotice":"⚠ 一分钟能量隔离必须「停、关、放」三同时，严禁先报告后处置延误窗口。"}', 2);
INSERT INTO fac_emergency_node_guidance (node_id, detail_json, sort_no) VALUES ('3', '{"nodeId":"3","nodeName":"节点 3：三分钟退守稳态","reportingChain":[{"step":1,"fromRole":"运行部主管 (李主管)","toRole":"装置区应急指挥部","method":"应急指挥专线","notice":"报告三分钟退守稳态完成情况并申请装置区预案评定"}],"roleTasks":[{"roleName":"内操","roleTitle":"工艺主操","personName":"张建国","avatarIcon":"🧑‍💻","phone":"139-0668-2233","tasks":["执行降温降压曲线，确保塔压平稳下降","记录关键参数变化并同步指挥部"]},{"roleName":"外操","roleTitle":"现场操作员","personName":"王安全","avatarIcon":"🧑‍🔧","phone":"137-0668-8378","tasks":["确认导空管线畅通并完成系统隔离","对泄漏点周边进行气体浓度复测"]},{"roleName":"班长","roleTitle":"运行部值班长","personName":"李明辉","avatarIcon":"🧑‍💼","phone":"138-0288-3456","tasks":["组织退守稳态评估","判断是否达到装置区预案启动条件"]}],"generalNotice":"⚠ 三分钟退守稳态是工艺安全的最后窗口，评估不达标必须果断升级。"}', 3);
INSERT INTO fac_emergency_node_guidance (node_id, detail_json, sort_no) VALUES ('4', '{"nodeId":"4","nodeName":"节点 4：五分钟消气防控险","reportingChain":[{"step":1,"fromRole":"装置区消防队长","toRole":"装置区应急指挥部","method":"对讲机专频","notice":"报告水幕隔离与浓度监测进展，申请增援"}],"roleTasks":[{"roleName":"内操","roleTitle":"DCS 主操","personName":"张建国","avatarIcon":"🧑‍💻","phone":"139-0668-2233","tasks":["持续监视 GDS 浓度曲线","联动消防水系统增压"]},{"roleName":"外操","roleTitle":"消防战斗员","personName":"王安全","avatarIcon":"🧑‍🔧","phone":"137-0668-8378","tasks":["操作水幕炮实施隔离稀释","下风向 100m 警戒与人员清点"]},{"roleName":"班长","roleTitle":"装置区指挥","personName":"李明辉","avatarIcon":"🧑‍💼","phone":"138-0288-3456","tasks":["评估控险效果","决定是否升级全厂应急"]}],"generalNotice":"⚠ 五分钟控险期间严禁中断水幕与监测，浓度反弹立即升级响应。"}', 4);
INSERT INTO fac_emergency_node_guidance (node_id, detail_json, sort_no) VALUES ('5', '{"nodeId":"5","nodeName":"节点 5：装置区应急","reportingChain":[{"step":1,"fromRole":"装置区指挥长","toRole":"各装置应急组","method":"应急广播","notice":"下达装置区专项预案启动指令"},{"step":2,"fromRole":"装置区指挥长","toRole":"公司应急指挥中心","method":"专线电话","notice":"同步报告装置区预案执行情况"}],"roleTasks":[{"roleName":"内操","roleTitle":"工艺主操","personName":"张建国","avatarIcon":"🧑‍💻","phone":"139-0668-2233","tasks":["开启二级雨水切断阀","执行物料二次隔离与平衡置换"]},{"roleName":"外操","roleTitle":"防化水炮操作员","personName":"王安全","avatarIcon":"🧑‍🔧","phone":"137-0668-8378","tasks":["操作高位水炮全覆盖降温","配合环保组截流污染水"]},{"roleName":"班长","roleTitle":"装置区指挥长","personName":"李明辉","avatarIcon":"🧑‍💼","phone":"138-0288-3456","tasks":["统筹装置区处置资源","评估是否升级全厂应急"]}],"generalNotice":"⚠ 装置区应急执行子阶段 5.1→5.2→5.3 顺序推进，禁止跳步。"}', 5);
INSERT INTO fac_emergency_node_guidance (node_id, detail_json, sort_no) VALUES ('6', '{"nodeId":"6","nodeName":"节点 6：全厂应急","reportingChain":[{"step":1,"fromRole":"公司总指挥","toRole":"各厂区/部门","method":"全厂应急广播","notice":"下达全厂预案启动指令并部署红线警戒"},{"step":2,"fromRole":"公司总指挥","toRole":"市应急管理局","method":"应急专线","notice":"报告全厂应急启动情况并请求政企联动"}],"roleTasks":[{"roleName":"内操","roleTitle":"调度主操","personName":"张建国","avatarIcon":"🧑‍💻","phone":"139-0668-2233","tasks":["启动事故池大功率抽排","配合全厂公用工程联锁"]},{"roleName":"外操","roleTitle":"警戒组","personName":"王安全","avatarIcon":"🧑‍🔧","phone":"137-0668-8378","tasks":["部署全厂防化警戒红线","引导外部增援车辆"]},{"roleName":"班长","roleTitle":"公司总指挥","personName":"李明辉","avatarIcon":"🧑‍💼","phone":"138-0288-3456","tasks":["统筹全厂资源","决定是否上报政府应急"]}],"generalNotice":"⚠ 全厂应急阶段信息发布统一归口，避免多口径造成混乱。"}', 6);
INSERT INTO fac_emergency_node_guidance (node_id, detail_json, sort_no) VALUES ('7', '{"nodeId":"7","nodeName":"节点 7：政府应急","reportingChain":[{"step":1,"fromRole":"市应急指挥部","toRole":"公安/交警/环保/120","method":"政府应急联动","notice":"全面介入并统一指挥"},{"step":2,"fromRole":"市应急指挥部","toRole":"茂名石化公司","method":"政企联席","notice":"明确企业配合边界与信息报送口径"}],"roleTasks":[{"roleName":"内操","roleTitle":"企业联络员","personName":"张建国","avatarIcon":"🧑‍💻","phone":"139-0668-2233","tasks":["向政府提供实时工艺数据","配合环保监测数据接入"]},{"roleName":"外操","roleTitle":"现场配合组","personName":"王安全","avatarIcon":"🧑‍🔧","phone":"137-0668-8378","tasks":["配合政府力量开展社区疏散","维护现场秩序"]},{"roleName":"班长","roleTitle":"企业总指挥","personName":"李明辉","avatarIcon":"🧑‍💼","phone":"138-0288-3456","tasks":["对接政府指挥部","统一对外信息发布"]}],"generalNotice":"⚠ 政府应急阶段企业服从统一指挥，信息发布以政府口径为准。"}', 7);
INSERT INTO fac_emergency_node_guidance (node_id, detail_json, sort_no) VALUES ('8', '{"nodeId":"8","nodeName":"节点 8：完成处置","reportingChain":[{"step":1,"fromRole":"现场指挥","toRole":"公司应急指挥中心","method":"专线电话","notice":"报告泄漏封堵与浓度达标情况，申请解除警戒"}],"roleTasks":[{"roleName":"内操","roleTitle":"工艺主操","personName":"张建国","avatarIcon":"🧑‍💻","phone":"139-0668-2233","tasks":["确认 DCS 参数恢复正常","记录处置过程数据"]},{"roleName":"外操","roleTitle":"现场复测员","personName":"王安全","avatarIcon":"🧑‍🔧","phone":"137-0668-8378","tasks":["复测气体浓度达标","配合解除警戒恢复通行"]},{"roleName":"班长","roleTitle":"现场指挥","personName":"李明辉","avatarIcon":"🧑‍💼","phone":"138-0288-3456","tasks":["确认无二次衍生隐患","下达处置完成指令"]}],"generalNotice":"⚠ 完成处置前必须“三复测”：浓度、温度、泄漏点，全部达标方可解除。"}', 8);
INSERT INTO fac_emergency_node_guidance (node_id, detail_json, sort_no) VALUES ('9', '{"nodeId":"9","nodeName":"节点 9：总结与恢复","reportingChain":[{"step":1,"fromRole":"总结评估组","toRole":"公司应急指挥中心","method":"书面报告","notice":"提交事故调查报告与恢复生产评估"}],"roleTasks":[{"roleName":"内操","roleTitle":"数据整理员","personName":"张建国","avatarIcon":"🧑‍💻","phone":"139-0668-2233","tasks":["整理工艺曲线与报警记录","配合事故原因分析"]},{"roleName":"外操","roleTitle":"现场恢复组","personName":"王安全","avatarIcon":"🧑‍🔧","phone":"137-0668-8378","tasks":["现场清理与设备检查","恢复生产条件确认"]},{"roleName":"班长","roleTitle":"应急办主任","personName":"李明辉","avatarIcon":"🧑‍💼","phone":"138-0288-3456","tasks":["组织复盘与整改","归档应急全过程记录"]}],"generalNotice":"⚠ 总结阶段重点复盘“135”各节点用时与响应质量，形成整改闭环。"}', 9);
