-- V5 消防报警域：消防报警分页列表（火灾/烟雾/GDS/设备故障）
-- 种子平移自前端 FIRE_ALARM_TEMPLATES（src/services/alarm.ts），保证 UI 展示一致且为真实数据

CREATE TABLE fac_fire_alarm (
    alarm_id            VARCHAR(32) PRIMARY KEY,
    type_label          VARCHAR(32),
    type_tone           VARCHAR(16),
    source              VARCHAR(32),
    object_type         VARCHAR(32),
    object_name         VARCHAR(64),
    level               VARCHAR(16),
    description         VARCHAR(256),
    location            VARCHAR(128),
    time                VARCHAR(32),
    false_alarm         VARCHAR(16),
    status              VARCHAR(16),
    rescue_event_id     VARCHAR(32),
    monitor_id          VARCHAR(64),
    monitor_label       VARCHAR(128),
    onsite_monitor_id   VARCHAR(64),
    onsite_monitor_label VARCHAR(128),
    title               VARCHAR(128)
);
INSERT INTO fac_fire_alarm (alarm_id, type_label, type_tone, source, object_type, object_name, level, description, location, false_alarm, status, rescue_event_id, monitor_id, monitor_label, onsite_monitor_id, onsite_monitor_label, title, time) VALUES ('FA-20260907-001', '火灾报警', 'fire', '火灾报警', '装置', '蜡油加氢装置', '-', '蜡油加氢装置区疑似出现明火，请核实。', '化工区-蜡油加氢装置区', '未核实', 'ACTIVE', '1', 'cam-a-east', '蜡油加氢东侧监控', 'cam-a-site', '蜡油加氢现场监控', '蜡油加氢装置火灾', '2026-05-31 10:14:12');
INSERT INTO fac_fire_alarm (alarm_id, type_label, type_tone, source, object_type, object_name, level, description, location, false_alarm, status, rescue_event_id, monitor_id, monitor_label, onsite_monitor_id, onsite_monitor_label, title, time) VALUES ('FA-20260907-002', '烟雾报警', 'smoke', '火灾报警', '储罐', '储罐区B-3', '-', '储罐区B-3顶部烟雾浓度异常升高，请现场复核。', '储运区-储罐区B-3', '否', 'ACTIVE', '2', 'cam-tank-b3', '储罐区B-3监控', 'cam-tank-b3-site', '储罐区现场监控', '储罐区B-3烟雾', '2026-05-31 11:15:13');
INSERT INTO fac_fire_alarm (alarm_id, type_label, type_tone, source, object_type, object_name, level, description, location, false_alarm, status, rescue_event_id, monitor_id, monitor_label, onsite_monitor_id, onsite_monitor_label, title, time) VALUES ('FA-20260907-003', 'GDS报警', 'gds', 'DCS/GDS', '装置', '催化裂化装置', '高高报', '催化裂化装置可燃气检测点浓度超限，请立即处置。', '炼油区-催化裂化装置', '未核实', 'ACTIVE', '3', 'cam-fcc-01', '催化裂化监控', 'cam-fcc-site', '催化裂化现场监控', '催化裂化GDS报警', '2026-05-31 12:16:14');
INSERT INTO fac_fire_alarm (alarm_id, type_label, type_tone, source, object_type, object_name, level, description, location, false_alarm, status, rescue_event_id, monitor_id, monitor_label, onsite_monitor_id, onsite_monitor_label, title, time) VALUES ('FA-20260907-004', '烟雾报警', 'muted', '视频识别', '仓库', '仓储区A库', '-', '仓储区A库视频监控识别烟雾，经核实为维保测试，已关闭。', '仓储区-A库', '是', 'CLOSED', '4', 'cam-store-a', '仓储区监控', 'cam-store-site', '仓库现场监控', '仓储区A库烟雾', '2026-05-30 13:17:15');
INSERT INTO fac_fire_alarm (alarm_id, type_label, type_tone, source, object_type, object_name, level, description, location, false_alarm, status, rescue_event_id, monitor_id, monitor_label, onsite_monitor_id, onsite_monitor_label, title, time) VALUES ('FA-20260907-005', '火灾报警', 'fire', '火灾报警', '装置', '重整装置', '-', '重整装置泵房感温电缆报警，请派员现场确认。', '化工区-重整装置泵房', '否', 'ACTIVE', '5', 'cam-reform-01', '重整装置监控', 'cam-reform-site', '重整现场监控', '重整装置火灾', '2026-05-30 14:18:16');
INSERT INTO fac_fire_alarm (alarm_id, type_label, type_tone, source, object_type, object_name, level, description, location, false_alarm, status, rescue_event_id, monitor_id, monitor_label, onsite_monitor_id, onsite_monitor_label, title, time) VALUES ('FA-20260907-006', 'GDS报警', 'gds', 'DCS/GDS', '管网', '火炬系统', '高报', '火炬系统周边可燃气检测短时波动，请关注。', '公用工程区-火炬系统', '未核实', 'ACTIVE', '6', 'cam-torch-01', '火炬系统监控', 'cam-torch-site', '火炬系统现场监控', '火炬系统GDS', '2026-05-30 15:19:17');
INSERT INTO fac_fire_alarm (alarm_id, type_label, type_tone, source, object_type, object_name, level, description, location, false_alarm, status, rescue_event_id, monitor_id, monitor_label, onsite_monitor_id, onsite_monitor_label, title, time) VALUES ('FA-20260907-007', '设备故障', 'muted', '火灾报警', '装置', '蜡油加氢装置', '-', '感烟探测器通讯中断，已派维保人员检修。', '化工区-蜡油加氢装置区', '否', 'CLOSED', '7', 'cam-a-east', '蜡油加氢东侧监控', 'cam-a-site', '蜡油加氢现场监控', '蜡油加氢设备故障', '2026-05-29 16:20:18');
INSERT INTO fac_fire_alarm (alarm_id, type_label, type_tone, source, object_type, object_name, level, description, location, false_alarm, status, rescue_event_id, monitor_id, monitor_label, onsite_monitor_id, onsite_monitor_label, title, time) VALUES ('FA-20260907-008', '火灾报警', 'fire', '人工上报', '储罐', '储罐区B-3', '-', '巡检人员报告储罐区有异味，请联动气体检测复核。', '储运区-储罐区B-3', '未核实', 'ACTIVE', '8', 'cam-tank-b3', '储罐区B-3监控', 'cam-tank-b3-site', '储罐区现场监控', '储罐区人工上报', '2026-05-29 17:21:19');
INSERT INTO fac_fire_alarm (alarm_id, type_label, type_tone, source, object_type, object_name, level, description, location, false_alarm, status, rescue_event_id, monitor_id, monitor_label, onsite_monitor_id, onsite_monitor_label, title, time) VALUES ('FA-20260907-009', '烟雾报警', 'smoke', '视频识别', '装置', '催化裂化装置', '-', '催化裂化装置西侧视频识别到烟雾团，请核实。', '炼油区-催化裂化装置西侧', '否', 'ACTIVE', '9', 'cam-fcc-01', '催化裂化监控', 'cam-fcc-site', '催化裂化现场监控', '催化裂化烟雾', '2026-05-29 10:22:20');
INSERT INTO fac_fire_alarm (alarm_id, type_label, type_tone, source, object_type, object_name, level, description, location, false_alarm, status, rescue_event_id, monitor_id, monitor_label, onsite_monitor_id, onsite_monitor_label, title, time) VALUES ('FA-20260907-010', 'GDS报警', 'gds', 'DCS/GDS', '装置', '蜡油加氢装置', '高高报', '蜡油加氢装置硫化氢检测点高高报，请启动应急预案。', '化工区-蜡油加氢装置区', '否', 'ACTIVE', '10', 'cam-a-east', '蜡油加氢东侧监控', 'cam-a-site', '蜡油加氢现场监控', '蜡油加氢GDS高高报', '2026-05-28 11:23:21');
INSERT INTO fac_fire_alarm (alarm_id, type_label, type_tone, source, object_type, object_name, level, description, location, false_alarm, status, rescue_event_id, monitor_id, monitor_label, onsite_monitor_id, onsite_monitor_label, title, time) VALUES ('FA-20260907-011', '火灾报警', 'fire', '火灾报警', '装置', '蜡油加氢装置', '-', '蜡油加氢装置区疑似出现明火，请核实。', '化工区-蜡油加氢装置区', '未核实', 'ACTIVE', '1', 'cam-a-east', '蜡油加氢东侧监控', 'cam-a-site', '蜡油加氢现场监控', '蜡油加氢装置火灾', '2026-05-28 12:24:22');
INSERT INTO fac_fire_alarm (alarm_id, type_label, type_tone, source, object_type, object_name, level, description, location, false_alarm, status, rescue_event_id, monitor_id, monitor_label, onsite_monitor_id, onsite_monitor_label, title, time) VALUES ('FA-20260907-012', '烟雾报警', 'smoke', '火灾报警', '储罐', '储罐区B-3', '-', '储罐区B-3顶部烟雾浓度异常升高，请现场复核。', '储运区-储罐区B-3', '否', 'ACTIVE', '2', 'cam-tank-b3', '储罐区B-3监控', 'cam-tank-b3-site', '储罐区现场监控', '储罐区B-3烟雾', '2026-05-28 13:25:23');
INSERT INTO fac_fire_alarm (alarm_id, type_label, type_tone, source, object_type, object_name, level, description, location, false_alarm, status, rescue_event_id, monitor_id, monitor_label, onsite_monitor_id, onsite_monitor_label, title, time) VALUES ('FA-20260907-013', 'GDS报警', 'gds', 'DCS/GDS', '装置', '催化裂化装置', '高高报', '催化裂化装置可燃气检测点浓度超限，请立即处置。', '炼油区-催化裂化装置', '未核实', 'ACTIVE', '3', 'cam-fcc-01', '催化裂化监控', 'cam-fcc-site', '催化裂化现场监控', '催化裂化GDS报警', '2026-05-27 14:26:24');
INSERT INTO fac_fire_alarm (alarm_id, type_label, type_tone, source, object_type, object_name, level, description, location, false_alarm, status, rescue_event_id, monitor_id, monitor_label, onsite_monitor_id, onsite_monitor_label, title, time) VALUES ('FA-20260907-014', '烟雾报警', 'muted', '视频识别', '仓库', '仓储区A库', '-', '仓储区A库视频监控识别烟雾，经核实为维保测试，已关闭。', '仓储区-A库', '是', 'CLOSED', '4', 'cam-store-a', '仓储区监控', 'cam-store-site', '仓库现场监控', '仓储区A库烟雾', '2026-05-27 15:27:25');
INSERT INTO fac_fire_alarm (alarm_id, type_label, type_tone, source, object_type, object_name, level, description, location, false_alarm, status, rescue_event_id, monitor_id, monitor_label, onsite_monitor_id, onsite_monitor_label, title, time) VALUES ('FA-20260907-015', '火灾报警', 'fire', '火灾报警', '装置', '重整装置', '-', '重整装置泵房感温电缆报警，请派员现场确认。', '化工区-重整装置泵房', '否', 'ACTIVE', '5', 'cam-reform-01', '重整装置监控', 'cam-reform-site', '重整现场监控', '重整装置火灾', '2026-05-27 16:28:26');
INSERT INTO fac_fire_alarm (alarm_id, type_label, type_tone, source, object_type, object_name, level, description, location, false_alarm, status, rescue_event_id, monitor_id, monitor_label, onsite_monitor_id, onsite_monitor_label, title, time) VALUES ('FA-20260907-016', 'GDS报警', 'gds', 'DCS/GDS', '管网', '火炬系统', '高报', '火炬系统周边可燃气检测短时波动，请关注。', '公用工程区-火炬系统', '未核实', 'ACTIVE', '6', 'cam-torch-01', '火炬系统监控', 'cam-torch-site', '火炬系统现场监控', '火炬系统GDS', '2026-05-26 17:29:27');
