#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
达梦迁移的「自增列」适配（一次性改写器，默认 dry-run）。

背景（2026-09-17 DM8 首次实跑结论）：
  1. DM8 不认 Oracle 风格的 `GENERATED BY DEFAULT AS IDENTITY`（[-2007] 语法分析出错），
     项目实体用的是 MyBatis-Plus `IdType.AUTO`（依赖 DB 自增）→ 必须改成 DM8 的 `IDENTITY(1,1)`。
  2. DM8 的 IDENTITY 列**不允许显式插入 id**（[-2723]：须 SET IDENTITY_INSERT 为 ON），
     而种子 INSERT 全部显式给 id → 必须在插入前后包 `SET IDENTITY_INSERT <表> ON/OFF`。

改写规则：
  A. `GENERATED BY DEFAULT AS IDENTITY`  ->  `IDENTITY(1,1)`（仅限含该字样的语句）
  B. 对「INSERT INTO <identity表> 且列清单含 id」的语句：
       - 与上一条 INSERT 不同表 -> 先补 `SET IDENTITY_INSERT <旧表> OFF;`（如有）再 `... <新表> ON;`
       - 遇到任何非 INSERT 语句 -> 如有未关闭的 ON，补 OFF
       - 文件末尾如仍 ON，补 OFF
     identity 表集合跨文件累计（V1 建的表 V2 也能种）。

保留原行尾；不改注释/空行排版，diff 只含「替换的自增写法」与「插入的 SET 行」。

用法：
  python scripts/adapt-dameng-identity.py --migration-dir src/main/resources/db/migration            # dry-run
  python scripts/adapt-dameng-identity.py --migration-dir src/main/resources/db/migration --apply
"""
import argparse
import os
import re
import sys

IDENT_RE = re.compile(r"\bGENERATED\s+BY\s+DEFAULT\s+AS\s+IDENTITY", re.I)
CREATE_RE = re.compile(r"\bCREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?[\"`]?([A-Za-z_][\w$]*)[\"`]?", re.I)
INSERT_RE = re.compile(r"\bINSERT\s+INTO\s+[\"`]?([A-Za-z_][\w$]*)[\"`]?", re.I)


def split_statements(text):
    """按顶层 ';' 切分，返回 [(起始偏移, 语句文本)]；字符串/注释内的 ';' 不切。"""
    out, buf, start = [], [], 0
    i, n, in_str = 0, len(text), False
    while i < n:
        c = text[i]
        if in_str:
            buf.append(c)
            if c == "'":
                if i + 1 < n and text[i + 1] == "'":
                    buf.append("'"); i += 1
                else:
                    in_str = False
        elif c == "'":
            in_str = True; buf.append(c)
        elif c == "-" and i + 1 < n and text[i + 1] == "-":
            j = text.find("\n", i)
            j = n if j == -1 else j
            buf.append(text[i:j]); i = j - 1
        elif c == "/" and i + 1 < n and text[i + 1] == "*":
            j = text.find("*/", i)
            j = n if j == -1 else j + 2
            buf.append(text[i:j]); i = j - 1
        elif c == ";":
            buf.append(c)
            out.append((start, "".join(buf)))
            buf = []
            start = i + 1
        else:
            buf.append(c)
        i += 1
    tail = "".join(buf)
    if tail.strip():
        out.append((start, tail))
    return out


def code_of(stmt):
    """去掉注释后的可执行文本（用于判断语句类型）。"""
    s = re.sub(r"/\*.*?\*/", " ", stmt, flags=re.S)
    s = re.sub(r"--[^\n]*", " ", s)
    return s.strip()


def columns_of(code, table):
    """取 INSERT INTO <table> 后的列清单，返回小写列名集合；无列清单返回 None。"""
    m = re.search(r"\bINSERT\s+INTO\s+[\"`]?%s[\"`]?\s*(\([^)]*\))" % re.escape(table), code, re.I)
    if not m:
        return None
    cols = {c.strip().strip('"`').lower() for c in m.group(1)[1:-1].split(",")}
    return {c for c in cols if c}


def adapt(text, identity_tables):
    """返回 (新文本, 统计)。identity_tables 为跨文件累计的可变集合。"""
    nl = "\r\n" if "\r\n" in text else "\n"
    stmts = split_statements(text)
    edits = []          # (位置, 插入文本)
    replaced = 0
    cur = None          # 当前 IDENTITY_INSERT 打开的表

    for pos, stmt in stmts:
        code = code_of(stmt)
        if not code:
            continue
        m = INSERT_RE.match(code)
        if m:
            tbl = m.group(1).lower()
            need = tbl in identity_tables
            if need:
                cols = columns_of(code, tbl)
                need = cols is None or "id" in cols     # 无列清单视作含 id
            if need:
                if cur != tbl:
                    if cur:
                        edits.append((pos, "SET IDENTITY_INSERT %s OFF;" % cur))
                    edits.append((pos, "SET IDENTITY_INSERT %s ON;" % tbl))
                    cur = tbl
            elif cur:
                edits.append((pos, "SET IDENTITY_INSERT %s OFF;" % cur))
                cur = None
        else:
            if cur:
                edits.append((pos, "SET IDENTITY_INSERT %s OFF;" % cur))
                cur = None

        if IDENT_RE.search(stmt):
            replaced += 1

    # 文件末尾收口
    if cur:
        edits.append((len(text), "SET IDENTITY_INSERT %s OFF;" % cur))

    # 应用插入（先做！）：edits 的偏移是基于「原始文本」算的，
    # 若先做 IDENTITY 替换（会缩短文本），偏移就会错位、SET 被插进多行语句中间。
    for pos in sorted({p for p, _ in edits}, reverse=True):
        ins = [t for p, t in edits if p == pos]
        # 该位置若同时有 OFF 与 ON，先 OFF 再 ON
        offs = [t for t in ins if t.endswith("OFF;")]
        ons = [t for t in ins if t.endswith("ON;")]
        chunk = nl + nl.join(offs + ons) + nl
        text = text[:pos] + chunk + text[pos:]

    # 再做自增写法替换（插入的 SET 行不含该字样，互不影响）
    new_text = IDENT_RE.sub("IDENTITY(1,1)", text)

    stats = {"identity_replaced": replaced, "set_inserted": len(edits)}
    return new_text, stats


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--migration-dir", required=True)
    ap.add_argument("--dialect", default="dameng")
    ap.add_argument("--apply", action="store_true")
    args = ap.parse_args()

    d = os.path.join(args.migration_dir, args.dialect)
    if not os.path.isdir(d):
        print("[ERR] dir not found: %s" % d)
        sys.exit(2)

    files = sorted((f for f in os.listdir(d) if f.lower().endswith(".sql")),
                   key=lambda f: int(re.match(r"V(\d+)__", f).group(1)) if re.match(r"V(\d+)__", f) else 0)

    identity_tables = set()     # 跨文件累计
    tot_r = tot_s = touched = 0
    print("== %s ==" % ("APPLY" if args.apply else "DRY-RUN"))
    for fn in files:
        p = os.path.join(d, fn)
        with open(p, "rb") as fh:
            raw = fh.read().decode("utf-8")
        # 先把本文件要建的 identity 表并入集合（无论出现先后）
        for _, stmt in split_statements(raw):
            c = code_of(stmt)
            m = CREATE_RE.match(c)
            if m and re.search(r"\bIDENTITY\b", c, re.I):
                identity_tables.add(m.group(1).lower())
        new, st = adapt(raw, identity_tables)
        if new != raw:
            touched += 1
            tot_r += st["identity_replaced"]
            tot_s += st["set_inserted"]
            print("  %-42s IDENTITY替换 %3d  SET插入 %3d" % (fn, st["identity_replaced"], st["set_inserted"]))
            if args.apply:
                with open(p, "wb") as fh:
                    fh.write(new.encode("utf-8"))
    print("-- 共 %d 个文件改动；IDENTITY 替换 %d 处；SET IDENTITY_INSERT 插入 %d 行 --"
          % (touched, tot_r, tot_s))
    if not args.apply:
        print("   (dry-run；确认后加 --apply)")


if __name__ == "__main__":
    main()
