-- =============================================================================
-- V14 视频 —— 达梦 DM8 方言（Oracle 兼容，未实跑验证）
--   镜像自 h2/V14__video.sql。本文件未经达梦实例实跑验证，按 DM8 语法编写，需上环境复核。
-- =============================================================================

-- V14 视频控制/视频墙大屏真实数据源（fm-video-control / fm-video-wall）。
-- 数据来源：src/screen/lib/data/videoControlMock.ts、videoLinkageMock.ts 存量硬编码
-- （分类与分组树、摄像头分页网格、视频联动配置与规则），迁移后数值与文案语义保持不变。
-- 命名回避数据库保留字（value/left/top/type/status/level/count/command）：状态列名 status_name；
-- 分组树 id 沿用前端字符串编码（node_code / parent_code），联动配置沿用 config_code（lk-001...）。
-- 网格布局（1x1/2x2/3x3）与画面轮巡为前端交互状态，不在此建表。

CREATE TABLE fac_video_group (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_code VARCHAR2(32) NOT NULL,
    label VARCHAR2(64) NOT NULL,
    parent_code VARCHAR2(32),
    group_kind VARCHAR2(16) NOT NULL,
    icon_index NUMBER(9) NOT NULL DEFAULT 0,
    sort_no NUMBER(9) NOT NULL DEFAULT 0
)


CREATE TABLE fac_video_camera (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(64) NOT NULL,
    camera_type VARCHAR2(32) NOT NULL,
    location VARCHAR2(128),
    status_name VARCHAR2(16) NOT NULL DEFAULT 'live',
    hd NUMBER(1) NOT NULL DEFAULT 1,
    thumb_index NUMBER(9) NOT NULL DEFAULT 0,
    sort_no NUMBER(9) NOT NULL DEFAULT 0
)


CREATE TABLE fac_video_linkage (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_code VARCHAR2(32) NOT NULL,
    name VARCHAR2(64) NOT NULL,
    code VARCHAR2(64) NOT NULL,
    category VARCHAR2(32) NOT NULL,
    linkage_count NUMBER(9) NOT NULL DEFAULT 0,
    business_objects VARCHAR2(256),
    sort_no NUMBER(9) NOT NULL DEFAULT 0
)


CREATE TABLE fac_video_linkage_rule (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_code VARCHAR2(32) NOT NULL,
    preset_point VARCHAR2(64) NOT NULL,
    object_category VARCHAR2(32) NOT NULL,
    object_name VARCHAR2(64) NOT NULL,
    sort_no NUMBER(9) NOT NULL DEFAULT 0
)


-- 分类（group_kind=CATEGORY，8 个，沿用 videoControlMock.videoControlCategories）
INSERT INTO fac_video_group (node_code, label, parent_code, group_kind, icon_index, sort_no) VALUES ('refining', '炼油区', NULL, 'CATEGORY', 0, 1)
INSERT INTO fac_video_group (node_code, label, parent_code, group_kind, icon_index, sort_no) VALUES ('tank', '原油罐区', NULL, 'CATEGORY', 1, 2)
INSERT INTO fac_video_group (node_code, label, parent_code, group_kind, icon_index, sort_no) VALUES ('hazard', '重大危险源', NULL, 'CATEGORY', 2, 3)
INSERT INTO fac_video_group (node_code, label, parent_code, group_kind, icon_index, sort_no) VALUES ('production', '生产区', NULL, 'CATEGORY', 3, 4)
INSERT INTO fac_video_group (node_code, label, parent_code, group_kind, icon_index, sort_no) VALUES ('gate', '出入口', NULL, 'CATEGORY', 4, 5)
INSERT INTO fac_video_group (node_code, label, parent_code, group_kind, icon_index, sort_no) VALUES ('warehouse', '仓库', NULL, 'CATEGORY', 5, 6)
INSERT INTO fac_video_group (node_code, label, parent_code, group_kind, icon_index, sort_no) VALUES ('pump', '泵房', NULL, 'CATEGORY', 6, 7)
INSERT INTO fac_video_group (node_code, label, parent_code, group_kind, icon_index, sort_no) VALUES ('other', '其它区域', NULL, 'CATEGORY', 7, 8)


-- 分组树（group_kind=TREE，沿用 videoControlMock.videoControlTree）
INSERT INTO fac_video_group (node_code, label, parent_code, group_kind, icon_index, sort_no) VALUES ('drill', '应急演练', NULL, 'TREE', 0, 1)
INSERT INTO fac_video_group (node_code, label, parent_code, group_kind, icon_index, sort_no) VALUES ('drill-1', '演练1', 'drill', 'TREE', 0, 1)
INSERT INTO fac_video_group (node_code, label, parent_code, group_kind, icon_index, sort_no) VALUES ('drill-2', '演练2', 'drill', 'TREE', 0, 2)
INSERT INTO fac_video_group (node_code, label, parent_code, group_kind, icon_index, sort_no) VALUES ('event', '应急事件', NULL, 'TREE', 0, 2)
INSERT INTO fac_video_group (node_code, label, parent_code, group_kind, icon_index, sort_no) VALUES ('event-1', '事件1', 'event', 'TREE', 0, 1)
INSERT INTO fac_video_group (node_code, label, parent_code, group_kind, icon_index, sort_no) VALUES ('event-2', '事件2', 'event', 'TREE', 0, 2)
INSERT INTO fac_video_group (node_code, label, parent_code, group_kind, icon_index, sort_no) VALUES ('patrol', '日常巡检', NULL, 'TREE', 0, 3)
INSERT INTO fac_video_group (node_code, label, parent_code, group_kind, icon_index, sort_no) VALUES ('patrol-1', '巡检区域-1', 'patrol', 'TREE', 0, 1)
INSERT INTO fac_video_group (node_code, label, parent_code, group_kind, icon_index, sort_no) VALUES ('patrol-2', '巡检区域-2', 'patrol', 'TREE', 0, 2)
INSERT INTO fac_video_group (node_code, label, parent_code, group_kind, icon_index, sort_no) VALUES ('key', '重点监控', NULL, 'TREE', 0, 4)
INSERT INTO fac_video_group (node_code, label, parent_code, group_kind, icon_index, sort_no) VALUES ('key-1', '炼油罐区-5#球机', 'key', 'TREE', 0, 1)


-- 摄像头台账（27 路，沿用 videoControlMock.buildPageCells 生成规则：名称/类型循环、
-- 第 1 页第 2 格 loading、第 5 格 ai、thumbIndex = 序号 % 6）
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('炼油区-1', '固定点机', '中海壳牌石油化工有限公司', 'live', 1, 0, 1)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('炼油区-2', '球机', '中海壳牌石油化工有限公司', 'loading', 1, 1, 2)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('炼油区-3', '枪机', '中海壳牌石油化工有限公司', 'live', 1, 2, 3)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('催化区-1', '云台', '中海壳牌石油化工有限公司', 'live', 1, 3, 4)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('催化区-2', '固定点机', '中海壳牌石油化工有限公司', 'ai', 1, 4, 5)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('罐区-1', '球机', '中海壳牌石油化工有限公司', 'live', 1, 5, 6)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('罐区-2', '枪机', '中海壳牌石油化工有限公司', 'live', 1, 0, 7)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('罐区-3', '云台', '中海壳牌石油化工有限公司', 'live', 1, 1, 8)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('码头-1', '固定点机', '中海壳牌石油化工有限公司', 'live', 1, 2, 9)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('码头-2', '球机', '中海壳牌石油化工有限公司', 'live', 1, 3, 10)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('泵房-1', '枪机', '中海壳牌石油化工有限公司', 'live', 1, 4, 11)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('泵房-2', '云台', '中海壳牌石油化工有限公司', 'live', 1, 5, 12)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('仓库-1', '固定点机', '中海壳牌石油化工有限公司', 'live', 1, 0, 13)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('仓库-2', '球机', '中海壳牌石油化工有限公司', 'live', 1, 1, 14)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('出入口-1', '枪机', '中海壳牌石油化工有限公司', 'live', 1, 2, 15)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('出入口-2', '云台', '中海壳牌石油化工有限公司', 'live', 1, 3, 16)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('生产区-1', '固定点机', '中海壳牌石油化工有限公司', 'live', 1, 4, 17)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('生产区-2', '球机', '中海壳牌石油化工有限公司', 'live', 1, 5, 18)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('厂界-1', '枪机', '中海壳牌石油化工有限公司', 'live', 1, 0, 19)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('厂界-2', '云台', '中海壳牌石油化工有限公司', 'live', 1, 1, 20)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('装卸区-1', '固定点机', '中海壳牌石油化工有限公司', 'live', 1, 2, 21)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('装卸区-2', '球机', '中海壳牌石油化工有限公司', 'live', 1, 3, 22)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('办公区-1', '枪机', '中海壳牌石油化工有限公司', 'live', 1, 4, 23)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('办公区-2', '云台', '中海壳牌石油化工有限公司', 'live', 1, 5, 24)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('配电房-1', '固定点机', '中海壳牌石油化工有限公司', 'live', 1, 0, 25)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('配电房-2', '球机', '中海壳牌石油化工有限公司', 'live', 1, 1, 26)
INSERT INTO fac_video_camera (name, camera_type, location, status_name, hd, thumb_index, sort_no) VALUES ('消防站-1', '枪机', '中海壳牌石油化工有限公司', 'live', 1, 2, 27)


-- 视频联动配置（沿用 videoLinkageMock.videoLinkageConfigs）
INSERT INTO fac_video_linkage (config_code, name, code, category, linkage_count, business_objects, sort_no) VALUES ('lk-001', 'XX强3-2棚伯', 'HKJK-5124863', '枪机', 4, '石脑油罐区、催化裂化装置、催化氢解装置、储油罐区', 1)
INSERT INTO fac_video_linkage (config_code, name, code, category, linkage_count, business_objects, sort_no) VALUES ('lk-002', 'XX强3-5棚伯', 'HKJK-5124864', '枪机', 1, '石脑油罐区', 2)
INSERT INTO fac_video_linkage (config_code, name, code, category, linkage_count, business_objects, sort_no) VALUES ('lk-003', '1#厂区高空AR', 'HKJK-5124865', '高空AR', 2, 'A生产区、B生产区', 3)
INSERT INTO fac_video_linkage (config_code, name, code, category, linkage_count, business_objects, sort_no) VALUES ('lk-004', '北2路33#枪机', 'HKJK-5124866', '枪机', 3, '北2路、储油罐区、炼化厂区门口', 4)
INSERT INTO fac_video_linkage (config_code, name, code, category, linkage_count, business_objects, sort_no) VALUES ('lk-005', '储油罐区-2#球机', 'HKJK-5124867', '球机', 2, '储油罐区、消防水系统', 5)


-- 联动规则（沿用 videoLinkageMock.buildLinkageRules；未预置的配置由服务端回退默认规则）
INSERT INTO fac_video_linkage_rule (config_code, preset_point, object_category, object_name, sort_no) VALUES ('lk-001', '石脑油罐区-东南角', '重大危险源', '石脑油罐区', 1)
INSERT INTO fac_video_linkage_rule (config_code, preset_point, object_category, object_name, sort_no) VALUES ('lk-001', '催化裂化装置-北侧', '生产装置', '催化裂化装置', 2)
INSERT INTO fac_video_linkage_rule (config_code, preset_point, object_category, object_name, sort_no) VALUES ('lk-001', '催化氢解装置-西侧', '生产装置', '催化氢解装置', 3)
INSERT INTO fac_video_linkage_rule (config_code, preset_point, object_category, object_name, sort_no) VALUES ('lk-001', '储油罐区-西侧出入口', '储罐', '储油罐区', 4)
INSERT INTO fac_video_linkage_rule (config_code, preset_point, object_category, object_name, sort_no) VALUES ('lk-002', '石脑油罐区-东南角', '重大危险源', '石脑油罐区', 1)
INSERT INTO fac_video_linkage_rule (config_code, preset_point, object_category, object_name, sort_no) VALUES ('lk-003', '炼化厂区门口', '库区', 'A生产区', 1)
INSERT INTO fac_video_linkage_rule (config_code, preset_point, object_category, object_name, sort_no) VALUES ('lk-003', '北2路中段', '库区', 'B生产区', 2)
