-- =============================================================================
-- V1 全量快照（空库直达最新结构）—— 达梦 DM8 方言（Oracle 兼容）
--   双轨策略中的「完整快照」。后续 DDL 变更一律新增 V<yyyyMMddHHmmss>__<snake>.sql 增量文件。
--   列定义与 H2 / PostgreSQL 两套方言保持一致（仅类型映射不同）：
--     BIGINT/TINYINT -> NUMBER(19)/NUMBER(3)，自增主键用 GENERATED BY DEFAULT AS IDENTITY；
--     VARCHAR/TEXT/CLOB -> VARCHAR2/CLOB；BOOLEAN 标志位统一用 NUMBER(1)（0/1）；
--     CHAR(20) 设备物理主键、TIMESTAMP 时间列同源。
--   重要：达梦 DM8 在 Flyway 社区版无官方 database 模块，本文件无法在本机实跑验证，
--   仅按 DM8(Oracle 兼容) 语法编写，必须到达梦实例上复核执行。详见 application-dm.yml 注释。
-- =============================================================================

CREATE TABLE sys_user (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(64) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    real_name VARCHAR2(64),
    role VARCHAR2(32) DEFAULT 'VIEWER' NOT NULL,
    status NUMBER(3) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted NUMBER(1) DEFAULT 0 NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_sys_user_username UNIQUE (username)
);

CREATE TABLE sys_menu (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    parent_id NUMBER(19) DEFAULT 0,
    name VARCHAR2(64) NOT NULL,
    code VARCHAR2(128),
    path VARCHAR2(255),
    icon VARCHAR2(64),
    sort_order NUMBER(9) DEFAULT 0,
    status NUMBER(3) DEFAULT 1,
    deleted NUMBER(1) DEFAULT 0 NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE fac_device (
    device_code CHAR(20) PRIMARY KEY,
    device_name VARCHAR2(128) NOT NULL,
    device_type VARCHAR2(32),
    zone VARCHAR2(64),
    status NUMBER(3) DEFAULT 0 NOT NULL,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE fac_alarm (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    alarm_id VARCHAR2(32),
    device_code CHAR(20),
    level NUMBER(3) NOT NULL,
    type VARCHAR2(32),
    title VARCHAR2(255) NOT NULL,
    content CLOB,
    status NUMBER(3) DEFAULT 0 NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    location VARCHAR2(128),
    category VARCHAR2(32),
    warned NUMBER(1) DEFAULT 0,
    plan_id VARCHAR2(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted NUMBER(1) DEFAULT 0 NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_fac_alarm_alarm_id UNIQUE (alarm_id)
);

CREATE TABLE fac_workstation (
    workstation_id VARCHAR2(32) PRIMARY KEY,
    name VARCHAR2(128) NOT NULL,
    zone VARCHAR2(64),
    online NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE fac_audit_log (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    action VARCHAR2(128) NOT NULL,
    module VARCHAR2(128),
    detail_json CLOB,
    event_at NUMBER(19),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
