-- =============================================================================
-- V30 节点阶段配置 —— 达梦 DM8 方言（Oracle 兼容，未实跑验证）
--   镜像自 h2/V30__node_phase_config.sql。本文件未经达梦实例实跑验证，按 DM8 语法编写，需上环境复核。
-- =============================================================================

-- V30 应急流程「节点联动配置」真实数据源（fm-accident-rescue 应急指挥 · 节点联动配置弹窗）。
-- 数据来源：src/screen/lib/data/nodeConfigData.ts 的 DEFAULT_NODE_PHASE_CONFIGS（9 个流程节点：
-- 接警研判/1min/3min/5min/装置区/全厂/政府/完成处置/总结与恢复），迁移后数值与文案语义保持不变。
-- 列表字段（锚点优先级 / 右侧隐藏页签 / 左侧隐藏面板）以逗号连接的字符串落库，空串表示空集合，
-- 由服务端在读写时拆装为数组；custom_center 以 "lon,lat" 文本存储，空表示未配自定义坐标。
-- 命名回避数据库保留字（value/type/mode/time/seq）。

CREATE TABLE fac_node_phase_config (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id VARCHAR2(32) NOT NULL,
    node_name VARCHAR2(64) NOT NULL,
    camera_anchors VARCHAR2(256) NOT NULL DEFAULT '',
    custom_center VARCHAR2(64),
    buffer_radius_meters NUMBER(9) NOT NULL DEFAULT 260,
    right_hidden_tabs VARCHAR2(256) NOT NULL DEFAULT '',
    left_hidden_panels VARCHAR2(256) NOT NULL DEFAULT '',
    duty_auto_roster NUMBER(1) NOT NULL DEFAULT 0,
    sort_no NUMBER(9) NOT NULL DEFAULT 0
);


INSERT INTO fac_node_phase_config (node_id, node_name, camera_anchors, custom_center, buffer_radius_meters, right_hidden_tabs, left_hidden_panels, duty_auto_roster, sort_no) VALUES ('alarmJudgement', '1. 接警研判', 'alarm_phone_location,event_device,alarm_phone_zone,factory_center', NULL, 260, '', '', 1, 1);
INSERT INTO fac_node_phase_config (node_id, node_name, camera_anchors, custom_center, buffer_radius_meters, right_hidden_tabs, left_hidden_panels, duty_auto_roster, sort_no) VALUES ('1min', '2. 一分钟能量隔离', 'event_device,alarm_phone_zone,factory_center', NULL, 220, '', '', 1, 2);
INSERT INTO fac_node_phase_config (node_id, node_name, camera_anchors, custom_center, buffer_radius_meters, right_hidden_tabs, left_hidden_panels, duty_auto_roster, sort_no) VALUES ('3min', '3. 三分钟退守稳态', 'event_device,factory_center', NULL, 320, 'dynamics', 'info', 1, 3);
INSERT INTO fac_node_phase_config (node_id, node_name, camera_anchors, custom_center, buffer_radius_meters, right_hidden_tabs, left_hidden_panels, duty_auto_roster, sort_no) VALUES ('5min', '4. 五分钟消气防控险', 'event_device,first_responder_gps,factory_center', NULL, 380, 'auxiliary', 'info', 1, 4);
INSERT INTO fac_node_phase_config (node_id, node_name, camera_anchors, custom_center, buffer_radius_meters, right_hidden_tabs, left_hidden_panels, duty_auto_roster, sort_no) VALUES ('plantArea', '5. 装置区应急', 'event_device,alarm_phone_zone,factory_center', NULL, 460, '', 'info', 0, 5);
INSERT INTO fac_node_phase_config (node_id, node_name, camera_anchors, custom_center, buffer_radius_meters, right_hidden_tabs, left_hidden_panels, duty_auto_roster, sort_no) VALUES ('companyLevel', '6. 全厂应急', 'factory_center,event_device', NULL, 900, 'auxiliary', 'info', 0, 6);
INSERT INTO fac_node_phase_config (node_id, node_name, camera_anchors, custom_center, buffer_radius_meters, right_hidden_tabs, left_hidden_panels, duty_auto_roster, sort_no) VALUES ('govLevel', '7. 政府应急', 'factory_center', NULL, 1400, 'auxiliary,dynamics', 'info,plan', 0, 7);
INSERT INTO fac_node_phase_config (node_id, node_name, camera_anchors, custom_center, buffer_radius_meters, right_hidden_tabs, left_hidden_panels, duty_auto_roster, sort_no) VALUES ('handling', '8. 完成处置', 'event_device,factory_center', NULL, 300, '', 'info', 1, 8);
INSERT INTO fac_node_phase_config (node_id, node_name, camera_anchors, custom_center, buffer_radius_meters, right_hidden_tabs, left_hidden_panels, duty_auto_roster, sort_no) VALUES ('archive', '9. 总结与恢复', 'factory_center', NULL, 1200, 'auxiliary,dynamics', 'info,plan', 1, 9);
