-- =============================================================================
-- V32 系统管理域 RBAC 数据模型 —— 达梦 DM8 方言（Oracle 兼容）
--   与 H2 V32 对齐；列定义保持一致（仅类型映射不同）：
--     BIGINT AUTO_INCREMENT -> NUMBER(19) GENERATED BY DEFAULT AS IDENTITY；
--     TINYINT -> NUMBER(3)；INT -> NUMBER(9)；VARCHAR -> VARCHAR2。
--   重要：DM8 在 Flyway 社区版无官方 database 模块，本文件无法在本机实跑，
--        仅按 DM8(Oracle 兼容) 语法编写，必须到达梦实例上复核执行。
--   注意：本 dameng 迁移目录为迁移资产，全量重建时需补齐 V4–V25。
-- =============================================================================

CREATE TABLE sys_role (
    id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    role_code    VARCHAR2(64)  NOT NULL,
    role_name    VARCHAR2(64)  NOT NULL,
    description  VARCHAR2(255),
    data_scope   VARCHAR2(16)  DEFAULT 'SELF' NOT NULL,
    status       NUMBER(3)     DEFAULT 1 NOT NULL,
    built_in     NUMBER(3)     DEFAULT 0 NOT NULL,
    sort_order   NUMBER(9)     DEFAULT 0 NOT NULL,
    deleted      NUMBER(3)     DEFAULT 0 NOT NULL,
    created_at   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_sys_role_code UNIQUE (role_code)
);

CREATE TABLE sys_role_menu (
    id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    role_id     NUMBER(19) NOT NULL,
    menu_id     NUMBER(19) NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_sys_role_menu UNIQUE (role_id, menu_id)
);
CREATE INDEX idx_sys_role_menu_role ON sys_role_menu(role_id);

CREATE TABLE sys_dict_type (
    id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    dict_code    VARCHAR2(64)  NOT NULL,
    dict_name    VARCHAR2(64)  NOT NULL,
    description  VARCHAR2(255),
    status       NUMBER(3)     DEFAULT 1 NOT NULL,
    built_in     NUMBER(3)     DEFAULT 0 NOT NULL,
    deleted      NUMBER(3)     DEFAULT 0 NOT NULL,
    created_at   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_sys_dict_type_code UNIQUE (dict_code)
);

CREATE TABLE sys_dict_item (
    id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    dict_code    VARCHAR2(64)  NOT NULL,
    item_value   VARCHAR2(128) NOT NULL,
    item_label   VARCHAR2(128) NOT NULL,
    sort_order   NUMBER(9)     DEFAULT 0 NOT NULL,
    status       NUMBER(3)     DEFAULT 1 NOT NULL,
    description  VARCHAR2(255),
    deleted      NUMBER(3)     DEFAULT 0 NOT NULL,
    created_at   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE INDEX idx_sys_dict_item_code ON sys_dict_item(dict_code);

ALTER TABLE sys_menu ADD COLUMN menu_type VARCHAR2(16) DEFAULT 'MENU' NOT NULL;
ALTER TABLE sys_menu ADD COLUMN perm_code VARCHAR2(128);
ALTER TABLE sys_menu ADD COLUMN visible   NUMBER(3) DEFAULT 1 NOT NULL;

ALTER TABLE sys_user ADD COLUMN pwd_updated_at  TIMESTAMP;
ALTER TABLE sys_user ADD COLUMN must_change_pwd NUMBER(3) DEFAULT 0 NOT NULL;

UPDATE sys_menu SET menu_type = 'DIR' WHERE code LIKE 'fm-%';
