-- =============================================================================
-- V34 data_scope 行级 ABAC 地基 —— 达梦 DM8 方言（Oracle 兼容）
--   与 H2 V34 对齐；列定义保持一致（仅类型映射不同）：
--     BIGINT AUTO_INCREMENT -> NUMBER(19) GENERATED BY DEFAULT AS IDENTITY；
--     TINYINT -> NUMBER(3)；VARCHAR -> VARCHAR2。
--   说明：本 dameng 迁移目录为迁移资产，无法在本机实跑，须到达梦实例复核执行。
--   注意：DM8 逐条 INSERT（避免多行 VALUES 兼容性问题）。
-- =============================================================================

CREATE TABLE sys_zone (
    id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    zone_code   VARCHAR2(64)  NOT NULL,
    zone_name   VARCHAR2(64)  NOT NULL,
    sort_order  NUMBER(9)     DEFAULT 0 NOT NULL,
    status      NUMBER(3)     DEFAULT 1 NOT NULL,
    deleted     NUMBER(3)     DEFAULT 0 NOT NULL,
    created_at  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_sys_zone_code UNIQUE (zone_code)
);

ALTER TABLE sys_user ADD COLUMN zone_codes VARCHAR2(512);

INSERT INTO sys_zone (zone_code, zone_name, sort_order, status) VALUES ('LIANYOU', '炼油区', 1, 1);
INSERT INTO sys_zone (zone_code, zone_name, sort_order, status) VALUES ('YIXI', '乙烯区', 2, 1);
INSERT INTO sys_zone (zone_code, zone_name, sort_order, status) VALUES ('GUANQU', '罐区', 3, 1);
INSERT INTO sys_zone (zone_code, zone_name, sort_order, status) VALUES ('CANGCUN', '仓储区', 4, 1);
INSERT INTO sys_zone (zone_code, zone_name, sort_order, status) VALUES ('MATOU', '码头区', 5, 1);
INSERT INTO sys_zone (zone_code, zone_name, sort_order, status) VALUES ('FANGTING', '芳烃区', 6, 1);
INSERT INTO sys_zone (zone_code, zone_name, sort_order, status) VALUES ('TEQIN', '特勤保障区', 7, 1);
