-- =============================================================================
-- V37 视频墙导航数据源（达梦方言）—— 大屏「前端数据全后端化」P0-①
--   目的：把前端 screen/components/video-wall/videoWallStore.ts 内代码生成的
--         targetTree/videoTree/cameraTargetMap/defaultHighAltitudeCameras 迁到后端，
--         由新增 GET /api/v1/video/wall-navigation 提供。
--   建模：单表 fac_video_wall_node 承载四类节点（node_kind 区分）：
--         CATEGORY(6) / AREA(5) / HIGH_AR(4) 为真实行；TARGET(120) 为业务对象行，
--         行上携带 parent_code(所属分类) + area_code(所属厂区) + cam_count(通道数)。
--   派生：摄像头通道（v-{i}-{j}，j=1..cam_count）与其→目标映射由服务端按 TARGET 行
--         确定性派生（占位通道命名，接真实 MDM 设备后改读设备表），不单独建表。
--   口径：节点编码/名称与前端原生成逻辑逐位对齐（本文件由脚本生成，勿手改数值）。
--   与 h2/V37 同内容；达梦逐条 INSERT（不使用多行 VALUES）。
-- =============================================================================

CREATE TABLE fac_video_wall_node (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_code VARCHAR2(32) NOT NULL,
    node_kind VARCHAR2(16) NOT NULL,
    label VARCHAR2(64) NOT NULL,
    parent_code VARCHAR2(32),
    area_code VARCHAR2(32),
    cam_count NUMBER(9) DEFAULT 0 NOT NULL,
    sort_no NUMBER(9) DEFAULT 0 NOT NULL
);

INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('cat-1', 'CATEGORY', '重大危险源', NULL, NULL, 0, 1);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('cat-2', 'CATEGORY', '生产装置', NULL, NULL, 0, 2);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('cat-3', 'CATEGORY', '厂区出入口', NULL, NULL, 0, 3);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('cat-4', 'CATEGORY', '仓储区域', NULL, NULL, 0, 4);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('cat-5', 'CATEGORY', '道路与管廊', NULL, NULL, 0, 5);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('cat-6', 'CATEGORY', '其他区域', NULL, NULL, 0, 6);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('area-1', 'AREA', '一号生产厂区', NULL, NULL, 0, 1);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('area-2', 'AREA', '二号生产厂区', NULL, NULL, 0, 2);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('area-3', 'AREA', '储罐与物流区', NULL, NULL, 0, 3);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('area-4', 'AREA', '动力公用工程区', NULL, NULL, 0, 4);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('area-5', 'AREA', '周界安全防范区', NULL, NULL, 0, 5);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('high-ar-1', 'HIGH_AR', '1#厂区高空AR·全景', NULL, NULL, 0, 1);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('high-ar-2', 'HIGH_AR', '炼油区高空AR·北向', NULL, NULL, 0, 2);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('high-ar-3', 'HIGH_AR', '化工区高空AR·东向', NULL, NULL, 0, 3);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('high-ar-4', 'HIGH_AR', '储运区高空AR·南向', NULL, NULL, 0, 4);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-1', 'TARGET', '危化储罐区装置#001', 'cat-1', 'area-1', 5, 1);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-2', 'TARGET', '危化储罐区装置#002', 'cat-1', 'area-1', 6, 2);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-3', 'TARGET', '危化储罐区装置#003', 'cat-1', 'area-1', 7, 3);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-4', 'TARGET', '危化储罐区装置#004', 'cat-1', 'area-1', 8, 4);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-5', 'TARGET', '危化储罐区装置#005', 'cat-1', 'area-1', 9, 5);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-6', 'TARGET', '危化储罐区装置#006', 'cat-1', 'area-1', 10, 6);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-7', 'TARGET', '危化储罐区装置#007', 'cat-1', 'area-1', 11, 7);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-8', 'TARGET', '危化储罐区装置#008', 'cat-1', 'area-1', 12, 8);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-9', 'TARGET', '危化储罐区装置#009', 'cat-1', 'area-1', 4, 9);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-10', 'TARGET', '危化储罐区装置#010', 'cat-1', 'area-1', 5, 10);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-11', 'TARGET', '危化储罐区装置#011', 'cat-1', 'area-1', 6, 11);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-12', 'TARGET', '危化储罐区装置#012', 'cat-1', 'area-1', 7, 12);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-13', 'TARGET', '危化储罐区装置#013', 'cat-1', 'area-1', 8, 13);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-14', 'TARGET', '危化储罐区装置#014', 'cat-1', 'area-1', 9, 14);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-15', 'TARGET', '危化储罐区装置#015', 'cat-1', 'area-1', 10, 15);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-16', 'TARGET', '危化储罐区装置#016', 'cat-1', 'area-1', 11, 16);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-17', 'TARGET', '危化储罐区装置#017', 'cat-1', 'area-1', 12, 17);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-18', 'TARGET', '危化储罐区装置#018', 'cat-1', 'area-1', 4, 18);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-19', 'TARGET', '危化储罐区装置#019', 'cat-1', 'area-1', 5, 19);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-20', 'TARGET', '危化储罐区装置#020', 'cat-1', 'area-1', 6, 20);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-21', 'TARGET', '反应装置区装置#021', 'cat-2', 'area-1', 7, 21);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-22', 'TARGET', '反应装置区装置#022', 'cat-2', 'area-1', 8, 22);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-23', 'TARGET', '反应装置区装置#023', 'cat-2', 'area-1', 9, 23);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-24', 'TARGET', '反应装置区装置#024', 'cat-2', 'area-1', 10, 24);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-25', 'TARGET', '反应装置区装置#025', 'cat-2', 'area-2', 11, 25);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-26', 'TARGET', '反应装置区装置#026', 'cat-2', 'area-2', 12, 26);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-27', 'TARGET', '反应装置区装置#027', 'cat-2', 'area-2', 4, 27);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-28', 'TARGET', '反应装置区装置#028', 'cat-2', 'area-2', 5, 28);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-29', 'TARGET', '反应装置区装置#029', 'cat-2', 'area-2', 6, 29);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-30', 'TARGET', '反应装置区装置#030', 'cat-2', 'area-2', 7, 30);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-31', 'TARGET', '反应装置区装置#031', 'cat-2', 'area-2', 8, 31);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-32', 'TARGET', '反应装置区装置#032', 'cat-2', 'area-2', 9, 32);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-33', 'TARGET', '反应装置区装置#033', 'cat-2', 'area-2', 10, 33);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-34', 'TARGET', '反应装置区装置#034', 'cat-2', 'area-2', 11, 34);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-35', 'TARGET', '反应装置区装置#035', 'cat-2', 'area-2', 12, 35);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-36', 'TARGET', '反应装置区装置#036', 'cat-2', 'area-2', 4, 36);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-37', 'TARGET', '反应装置区装置#037', 'cat-2', 'area-2', 5, 37);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-38', 'TARGET', '反应装置区装置#038', 'cat-2', 'area-2', 6, 38);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-39', 'TARGET', '反应装置区装置#039', 'cat-2', 'area-2', 7, 39);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-40', 'TARGET', '反应装置区装置#040', 'cat-2', 'area-2', 8, 40);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-41', 'TARGET', '厂区出入口装置#041', 'cat-3', 'area-2', 9, 41);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-42', 'TARGET', '厂区出入口装置#042', 'cat-3', 'area-2', 10, 42);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-43', 'TARGET', '厂区出入口装置#043', 'cat-3', 'area-2', 11, 43);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-44', 'TARGET', '厂区出入口装置#044', 'cat-3', 'area-2', 12, 44);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-45', 'TARGET', '厂区出入口装置#045', 'cat-3', 'area-2', 4, 45);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-46', 'TARGET', '厂区出入口装置#046', 'cat-3', 'area-2', 5, 46);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-47', 'TARGET', '厂区出入口装置#047', 'cat-3', 'area-2', 6, 47);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-48', 'TARGET', '厂区出入口装置#048', 'cat-3', 'area-2', 7, 48);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-49', 'TARGET', '厂区出入口装置#049', 'cat-3', 'area-3', 8, 49);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-50', 'TARGET', '厂区出入口装置#050', 'cat-3', 'area-3', 9, 50);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-51', 'TARGET', '厂区出入口装置#051', 'cat-3', 'area-3', 10, 51);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-52', 'TARGET', '厂区出入口装置#052', 'cat-3', 'area-3', 11, 52);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-53', 'TARGET', '厂区出入口装置#053', 'cat-3', 'area-3', 12, 53);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-54', 'TARGET', '厂区出入口装置#054', 'cat-3', 'area-3', 4, 54);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-55', 'TARGET', '厂区出入口装置#055', 'cat-3', 'area-3', 5, 55);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-56', 'TARGET', '厂区出入口装置#056', 'cat-3', 'area-3', 6, 56);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-57', 'TARGET', '厂区出入口装置#057', 'cat-3', 'area-3', 7, 57);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-58', 'TARGET', '厂区出入口装置#058', 'cat-3', 'area-3', 8, 58);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-59', 'TARGET', '厂区出入口装置#059', 'cat-3', 'area-3', 9, 59);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-60', 'TARGET', '厂区出入口装置#060', 'cat-3', 'area-3', 10, 60);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-61', 'TARGET', '仓储物流区装置#061', 'cat-4', 'area-3', 11, 61);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-62', 'TARGET', '仓储物流区装置#062', 'cat-4', 'area-3', 12, 62);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-63', 'TARGET', '仓储物流区装置#063', 'cat-4', 'area-3', 4, 63);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-64', 'TARGET', '仓储物流区装置#064', 'cat-4', 'area-3', 5, 64);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-65', 'TARGET', '仓储物流区装置#065', 'cat-4', 'area-3', 6, 65);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-66', 'TARGET', '仓储物流区装置#066', 'cat-4', 'area-3', 7, 66);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-67', 'TARGET', '仓储物流区装置#067', 'cat-4', 'area-3', 8, 67);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-68', 'TARGET', '仓储物流区装置#068', 'cat-4', 'area-3', 9, 68);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-69', 'TARGET', '仓储物流区装置#069', 'cat-4', 'area-3', 10, 69);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-70', 'TARGET', '仓储物流区装置#070', 'cat-4', 'area-3', 11, 70);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-71', 'TARGET', '仓储物流区装置#071', 'cat-4', 'area-3', 12, 71);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-72', 'TARGET', '仓储物流区装置#072', 'cat-4', 'area-3', 4, 72);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-73', 'TARGET', '仓储物流区装置#073', 'cat-4', 'area-4', 5, 73);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-74', 'TARGET', '仓储物流区装置#074', 'cat-4', 'area-4', 6, 74);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-75', 'TARGET', '仓储物流区装置#075', 'cat-4', 'area-4', 7, 75);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-76', 'TARGET', '仓储物流区装置#076', 'cat-4', 'area-4', 8, 76);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-77', 'TARGET', '仓储物流区装置#077', 'cat-4', 'area-4', 9, 77);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-78', 'TARGET', '仓储物流区装置#078', 'cat-4', 'area-4', 10, 78);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-79', 'TARGET', '仓储物流区装置#079', 'cat-4', 'area-4', 11, 79);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-80', 'TARGET', '仓储物流区装置#080', 'cat-4', 'area-4', 12, 80);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-81', 'TARGET', '道路管廊区装置#081', 'cat-5', 'area-4', 4, 81);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-82', 'TARGET', '道路管廊区装置#082', 'cat-5', 'area-4', 5, 82);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-83', 'TARGET', '道路管廊区装置#083', 'cat-5', 'area-4', 6, 83);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-84', 'TARGET', '道路管廊区装置#084', 'cat-5', 'area-4', 7, 84);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-85', 'TARGET', '道路管廊区装置#085', 'cat-5', 'area-4', 8, 85);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-86', 'TARGET', '道路管廊区装置#086', 'cat-5', 'area-4', 9, 86);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-87', 'TARGET', '道路管廊区装置#087', 'cat-5', 'area-4', 10, 87);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-88', 'TARGET', '道路管廊区装置#088', 'cat-5', 'area-4', 11, 88);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-89', 'TARGET', '道路管廊区装置#089', 'cat-5', 'area-4', 12, 89);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-90', 'TARGET', '道路管廊区装置#090', 'cat-5', 'area-4', 4, 90);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-91', 'TARGET', '道路管廊区装置#091', 'cat-5', 'area-4', 5, 91);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-92', 'TARGET', '道路管廊区装置#092', 'cat-5', 'area-4', 6, 92);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-93', 'TARGET', '道路管廊区装置#093', 'cat-5', 'area-4', 7, 93);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-94', 'TARGET', '道路管廊区装置#094', 'cat-5', 'area-4', 8, 94);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-95', 'TARGET', '道路管廊区装置#095', 'cat-5', 'area-4', 9, 95);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-96', 'TARGET', '道路管廊区装置#096', 'cat-5', 'area-4', 10, 96);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-97', 'TARGET', '道路管廊区装置#097', 'cat-5', 'area-5', 11, 97);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-98', 'TARGET', '道路管廊区装置#098', 'cat-5', 'area-5', 12, 98);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-99', 'TARGET', '道路管廊区装置#099', 'cat-5', 'area-5', 4, 99);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-100', 'TARGET', '道路管廊区装置#100', 'cat-5', 'area-5', 5, 100);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-101', 'TARGET', '辅助设施区装置#101', 'cat-6', 'area-5', 6, 101);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-102', 'TARGET', '辅助设施区装置#102', 'cat-6', 'area-5', 7, 102);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-103', 'TARGET', '辅助设施区装置#103', 'cat-6', 'area-5', 8, 103);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-104', 'TARGET', '辅助设施区装置#104', 'cat-6', 'area-5', 9, 104);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-105', 'TARGET', '辅助设施区装置#105', 'cat-6', 'area-5', 10, 105);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-106', 'TARGET', '辅助设施区装置#106', 'cat-6', 'area-5', 11, 106);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-107', 'TARGET', '辅助设施区装置#107', 'cat-6', 'area-5', 12, 107);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-108', 'TARGET', '辅助设施区装置#108', 'cat-6', 'area-5', 4, 108);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-109', 'TARGET', '辅助设施区装置#109', 'cat-6', 'area-5', 5, 109);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-110', 'TARGET', '辅助设施区装置#110', 'cat-6', 'area-5', 6, 110);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-111', 'TARGET', '辅助设施区装置#111', 'cat-6', 'area-5', 7, 111);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-112', 'TARGET', '辅助设施区装置#112', 'cat-6', 'area-5', 8, 112);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-113', 'TARGET', '辅助设施区装置#113', 'cat-6', 'area-5', 9, 113);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-114', 'TARGET', '辅助设施区装置#114', 'cat-6', 'area-5', 10, 114);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-115', 'TARGET', '辅助设施区装置#115', 'cat-6', 'area-5', 11, 115);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-116', 'TARGET', '辅助设施区装置#116', 'cat-6', 'area-5', 12, 116);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-117', 'TARGET', '辅助设施区装置#117', 'cat-6', 'area-5', 4, 117);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-118', 'TARGET', '辅助设施区装置#118', 'cat-6', 'area-5', 5, 118);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-119', 'TARGET', '辅助设施区装置#119', 'cat-6', 'area-5', 6, 119);
INSERT INTO fac_video_wall_node (node_code, node_kind, label, parent_code, area_code, cam_count, sort_no) VALUES ('t-120', 'TARGET', '辅助设施区装置#120', 'cat-6', 'area-5', 7, 120);
