-- =============================================================================
-- V38 消防态势大屏数据源（达梦方言）—— 大屏「前端数据全后端化」P0
--   目的同 h2/V38；与 h2/V38 同内容；达梦逐条 INSERT，VARCHAR2 / NUMBER IDENTITY。
-- =============================================================================

CREATE TABLE fac_fire_monitor_area (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_code VARCHAR2(32) NOT NULL,
    scope VARCHAR2(16) NOT NULL,
    area_name VARCHAR2(64) NOT NULL,
    status VARCHAR2(16) NOT NULL,
    status_label VARCHAR2(64) NOT NULL,
    equipment NUMBER(10) NOT NULL DEFAULT 0,
    cameras NUMBER(10) NOT NULL DEFAULT 0,
    personnel NUMBER(10) NOT NULL DEFAULT 0,
    sort_no NUMBER(10) NOT NULL DEFAULT 0
);

CREATE TABLE fac_fire_monitored_object (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    obj_name VARCHAR2(64) NOT NULL,
    status VARCHAR2(16) NOT NULL,
    detail VARCHAR2(128) NOT NULL,
    tone VARCHAR2(16) NOT NULL,
    sort_no NUMBER(10) NOT NULL DEFAULT 0
);

INSERT INTO fac_fire_monitor_area (area_code, scope, area_name, status, status_label, equipment, cameras, personnel, sort_no) VALUES ('refinery-1', 'refinery', '炼油一部装置区', 'normal', '运行正常', 128, 24, 16, 1);
INSERT INTO fac_fire_monitor_area (area_code, scope, area_name, status, status_label, equipment, cameras, personnel, sort_no) VALUES ('refinery-2', 'refinery', '储运罐区', 'attention', '2台设备离线', 96, 18, 9, 2);
INSERT INTO fac_fire_monitor_area (area_code, scope, area_name, status, status_label, equipment, cameras, personnel, sort_no) VALUES ('refinery-3', 'refinery', '芳烃联合装置', 'normal', '运行正常', 112, 21, 14, 3);
INSERT INTO fac_fire_monitor_area (area_code, scope, area_name, status, status_label, equipment, cameras, personnel, sort_no) VALUES ('refinery-4', 'refinery', '催化裂化装置区', 'normal', '运行正常', 118, 22, 15, 4);
INSERT INTO fac_fire_monitor_area (area_code, scope, area_name, status, status_label, equipment, cameras, personnel, sort_no) VALUES ('refinery-5', 'refinery', '加氢裂化装置区', 'normal', '运行正常', 104, 20, 12, 5);
INSERT INTO fac_fire_monitor_area (area_code, scope, area_name, status, status_label, equipment, cameras, personnel, sort_no) VALUES ('refinery-6', 'refinery', '西化学水泵房', 'attention', '1项巡检待办', 68, 12, 7, 6);
INSERT INTO fac_fire_monitor_area (area_code, scope, area_name, status, status_label, equipment, cameras, personnel, sort_no) VALUES ('chemical-1', 'chemical', '化工装置区', 'normal', '运行正常', 143, 31, 22, 7);
INSERT INTO fac_fire_monitor_area (area_code, scope, area_name, status, status_label, equipment, cameras, personnel, sort_no) VALUES ('chemical-2', 'chemical', '聚烯烃装置区', 'normal', '运行正常', 105, 19, 13, 8);
INSERT INTO fac_fire_monitor_area (area_code, scope, area_name, status, status_label, equipment, cameras, personnel, sort_no) VALUES ('chemical-3', 'chemical', '乙烯联合装置区', 'normal', '运行正常', 126, 25, 18, 9);
INSERT INTO fac_fire_monitor_area (area_code, scope, area_name, status, status_label, equipment, cameras, personnel, sort_no) VALUES ('chemical-4', 'chemical', '公用工程装置区', 'attention', '1台设备离线', 91, 17, 10, 10);
INSERT INTO fac_fire_monitor_area (area_code, scope, area_name, status, status_label, equipment, cameras, personnel, sort_no) VALUES ('port-1', 'port', '水东港储运区', 'normal', '运行正常', 87, 16, 11, 11);
INSERT INTO fac_fire_monitor_area (area_code, scope, area_name, status, status_label, equipment, cameras, personnel, sort_no) VALUES ('port-2', 'port', '博贺新港作业区', 'attention', '1项巡检待办', 74, 14, 8, 12);
INSERT INTO fac_fire_monitor_area (area_code, scope, area_name, status, status_label, equipment, cameras, personnel, sort_no) VALUES ('port-3', 'port', '输油管廊区', 'normal', '运行正常', 82, 19, 9, 13);
INSERT INTO fac_fire_monitor_area (area_code, scope, area_name, status, status_label, equipment, cameras, personnel, sort_no) VALUES ('port-4', 'port', '成品油码头区', 'normal', '运行正常', 65, 13, 8, 14);

INSERT INTO fac_fire_monitored_object (obj_name, status, detail, tone, sort_no) VALUES ('A装置区', '告警', '1起火灾告警处置中', 'danger', 1);
INSERT INTO fac_fire_monitored_object (obj_name, status, detail, tone, sort_no) VALUES ('储运罐区', '预警', '1项特级动火作业', 'warning', 2);
INSERT INTO fac_fire_monitored_object (obj_name, status, detail, tone, sort_no) VALUES ('芳烃联合装置', '正常', '128个感知点在线', 'normal', 3);
INSERT INTO fac_fire_monitored_object (obj_name, status, detail, tone, sort_no) VALUES ('西化学水泵房', '正常', '36个感知点在线', 'normal', 4);
