-- =============================================================================
-- V42 地图域「装置区信息牌」数据源（dameng方言）—— 大屏「前端数据全后端化」P1
--   目的：把 MaomingPetroCesiumMap 的 MAP_THEME.plantZonePopups(4)/plantZoneTealTags(4)
--         迁到后端，由 GET /api/v1/map/zone-signs 提供。
--   口径：与前端原硬编码逐位对齐。
-- =============================================================================

CREATE TABLE fac_map_zone_sign (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sign_kind VARCHAR2(8) NOT NULL,
    title VARCHAR2(32) NOT NULL,
    location VARCHAR2(32) NULL,
    status_text VARCHAR2(32) NOT NULL,
    status_level VARCHAR2(8) NULL,
    stat_value VARCHAR2(8) NULL,
    sort_no INT NOT NULL DEFAULT 0
);

INSERT INTO fac_map_zone_sign (sign_kind, title, location, status_text, status_level, stat_value, sort_no) VALUES ('ALERT', '反应器', '储罐区B-3', '异常', 'alert', NULL, 1);
INSERT INTO fac_map_zone_sign (sign_kind, title, location, status_text, status_level, stat_value, sort_no) VALUES ('ALERT', '反应器', '储罐区B-5', '异常', 'alert', NULL, 2);
INSERT INTO fac_map_zone_sign (sign_kind, title, location, status_text, status_level, stat_value, sort_no) VALUES ('ALERT', '反应器', '储罐区B-7', '异常', 'alert', NULL, 3);
INSERT INTO fac_map_zone_sign (sign_kind, title, location, status_text, status_level, stat_value, sort_no) VALUES ('ALERT', '反应器', '储罐区B-9', '异常', 'alert', NULL, 4);
INSERT INTO fac_map_zone_sign (sign_kind, title, location, status_text, status_level, stat_value, sort_no) VALUES ('TEAL', '储罐区', NULL, '液位正常', NULL, '85%', 1);
INSERT INTO fac_map_zone_sign (sign_kind, title, location, status_text, status_level, stat_value, sort_no) VALUES ('TEAL', '装置区', NULL, '液位正常', NULL, '82%', 2);
INSERT INTO fac_map_zone_sign (sign_kind, title, location, status_text, status_level, stat_value, sort_no) VALUES ('TEAL', '精制区', NULL, '液位正常', NULL, '78%', 3);
INSERT INTO fac_map_zone_sign (sign_kind, title, location, status_text, status_level, stat_value, sort_no) VALUES ('TEAL', '公用区', NULL, '液位正常', NULL, '91%', 4);
