-- =============================================================================
-- V8 应急参考资料 —— 达梦 DM8 方言（Oracle 兼容，未实跑验证）
--   镜像自 h2/V8__emergency_reference.sql。本文件未经达梦实例实跑验证，按 DM8 语法编写，需上环境复核。
-- =============================================================================

-- V8 应急参考配置真实数据源：将 strength / phones / knowledge / duty 从 Java 硬编码常量迁移至 DB 参考表。
-- 语义不变（仍为应急资源固定参考配置），但改为可维护的数据源，便于运营更新而无需改代码。
CREATE TABLE sys_emergency_strength (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR2(32) NOT NULL,
    count NUMBER(9) NOT NULL DEFAULT 0,
    icon VARCHAR2(64)
)

CREATE TABLE sys_emergency_phone (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(64) NOT NULL,
    number VARCHAR2(32) NOT NULL,
    category VARCHAR2(32)
)

CREATE TABLE sys_knowledge_item (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(128) NOT NULL,
    count NUMBER(9) NOT NULL DEFAULT 0,
    icon VARCHAR2(64)
)

CREATE TABLE sys_duty_member (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(64) NOT NULL,
    phone VARCHAR2(32),
    role VARCHAR2(32),
    department VARCHAR2(64),
    shift VARCHAR2(16)
)


INSERT INTO sys_emergency_strength (kind, count, icon) VALUES ('应急专家', 47, 'UserFilled')
INSERT INTO sys_emergency_strength (kind, count, icon) VALUES ('应急物资', 3510, 'Box')
INSERT INTO sys_emergency_strength (kind, count, icon) VALUES ('救援队伍', 12, 'Soldier')
INSERT INTO sys_emergency_strength (kind, count, icon) VALUES ('装备车辆', 28, 'Van')
INSERT INTO sys_emergency_strength (kind, count, icon) VALUES ('应急场所', 6, 'LocationFilled')
INSERT INTO sys_emergency_strength (kind, count, icon) VALUES ('医疗机构', 3, 'FirstAidKit')
INSERT INTO sys_emergency_strength (kind, count, icon) VALUES ('应急车辆', 18, 'Truck')
INSERT INTO sys_emergency_strength (kind, count, icon) VALUES ('消防设施', 42, 'Fire')


INSERT INTO sys_emergency_phone (name, number, category) VALUES ('消防报警', '119', '消防')
INSERT INTO sys_emergency_phone (name, number, category) VALUES ('医疗急救', '120', '医疗')
INSERT INTO sys_emergency_phone (name, number, category) VALUES ('公安报警', '110', '公安')
INSERT INTO sys_emergency_phone (name, number, category) VALUES ('厂内应急', '0668-2222111', '厂内应急')
INSERT INTO sys_emergency_phone (name, number, category) VALUES ('保卫值班', '0668-2222333', '保卫值班')


INSERT INTO sys_knowledge_item (title, count, icon) VALUES ('岗位应急处置卡', 158, 'Document')
INSERT INTO sys_knowledge_item (title, count, icon) VALUES ('火灾爆炸应急预案', 42, 'Files')
INSERT INTO sys_knowledge_item (title, count, icon) VALUES ('气体泄漏处置', 67, 'Warning')


INSERT INTO sys_duty_member (name, phone, role, department, shift) VALUES ('杨恒明', '13792536966', '值班领导', '全部', '白班')
INSERT INTO sys_duty_member (name, phone, role, department, shift) VALUES ('李伟', '13800138000', '值班员', '全部', '白班')
